version: '3.3'

services:
  db-ltmv:
    image: mysql:8.2
    command: --innodb-log-file-size=500M --innodb_strict_mode=0
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root

  dev-ltmv:
    depends_on:
      - db-ltmv
    image: rapporteket/ltmv-dev:weekly
    volumes:
      - ~/.ssh:/home/rstudio/.ssh
      - ~/.gitconfig:/home/rstudio/.gitconfig
    ports:
      - "8787:8787"
      - "3838:3838"
    dns:
      - 8.8.8.8
    restart: "no"
    environment:
      USERID: $USERID
      PASSWORD: password
      DB_HOST: db-ltmv
      DB_USER: root
      DB_PASS: root

  adminer-ltmv:
    depends_on:
      - db-ltmv
    image: adminer
    restart: "no"
    environment:
      ADMINER_PLUGINS: frames
    ports:
      - 8888:8080
