SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP TABLE IF EXISTS `alleVar`;
CREATE TABLE `alleVar` (
  `AvdRESH` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `SykehusNavn` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ForlopsID` int(9) NOT NULL,
  `PasientID` int(10) unsigned DEFAULT NULL,
  `P_LAST_FREG_DATE` date DEFAULT NULL,
  `P_REGDATE` date DEFAULT NULL,
  `Kjoenn` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PasientAlder` bigint(20) DEFAULT NULL,
  `OpprettetAv` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `SistOppdatertAv` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `P_SSNTYPE` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `P_SSNSUBTYPE` tinyint(3) DEFAULT NULL,
  `PostNr` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `Poststed` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `Kommune` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `KomunneNr` varchar(4) COLLATE utf8_danish_ci DEFAULT NULL,
  `FylkesNr` char(2) COLLATE utf8_danish_ci DEFAULT NULL,
  `Fylke` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvDoed` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Doedsdato` date DEFAULT NULL,
  `P_ADDR_TYPE` tinyint(3) DEFAULT NULL,
  `IS_STOPPED` varchar(3) COLLATE utf8_danish_ci DEFAULT NULL,
  `R_CENTREID` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `R_MCETYPE` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Historisk` varchar(3) COLLATE utf8_danish_ci DEFAULT NULL,
  `Behandlingsstar` date DEFAULT NULL,
  `R_CENTRE` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `R_CENTRENAME` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `RegionaltHelsef` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Sykehus` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Avdeling` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Kappilaer` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `NattligOksygenm` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ProsentAvTiden` decimal(4,1) DEFAULT NULL,
  `NattligHypovent` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AndelAvNattenM` decimal(4,1) DEFAULT NULL,
  `R_SPO2_AVG_PERC` decimal(4,1) DEFAULT NULL,
  `R_SPO2_AVG_PERC_MISS` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `ArteriellPCO2KP` decimal(3,1) DEFAULT NULL,
  `ArteriellPO2KPa` decimal(3,1) DEFAULT NULL,
  `BaseExcessMmolL` decimal(3,1) DEFAULT NULL,
  `KapillaerPCO2Va` decimal(3,1) DEFAULT NULL,
  `KapillaerPO2Vaa` decimal(3,1) DEFAULT NULL,
  `BaseExcessKapil` decimal(3,1) DEFAULT NULL,
  `ArteriellSPCO2KP` decimal(3,1) DEFAULT NULL,
  `VitalkapasitetS` decimal(3,2) DEFAULT NULL,
  `VitalkapasitetL` decimal(3,2) DEFAULT NULL,
  `FVKLiter` decimal(3,2) DEFAULT NULL,
  `FEV1LiterSek` decimal(3,2) DEFAULT NULL,
  `PEFcHostePEFLit` smallint(6) DEFAULT NULL,
  `HoeydeCm` smallint(6) DEFAULT NULL,
  `VektKg` decimal(4,1) DEFAULT NULL,
  `BMI` decimal(16,5) DEFAULT NULL,
  `ForsertVitalkap` decimal(4,1) DEFAULT NULL,
  `FEV1IProsentAvF` decimal(4,1) DEFAULT NULL,
  `R_DIAGNOSIS1` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `HovedDiag` varchar(150) COLLATE utf8_danish_ci DEFAULT NULL,
  `R_DIAGNOSIS2` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `BiDiag` varchar(150) COLLATE utf8_danish_ci DEFAULT NULL,
  `R_DIAGNOSIS2_OTHER` varchar(150) COLLATE utf8_danish_ci DEFAULT NULL,
  `MorgenHodepine` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Soevnvansker` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `SvekketHostekra` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Dagtidstretthet` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Dyspne` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `RegOppstart` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AntallDagerPaaS` smallint(6) DEFAULT NULL,
  `OmstendigheterV` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehandlingstidP` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Behandlingsmeto` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Frenikusstimula` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Respiratortilsl` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DatoForTrakeost` date DEFAULT NULL,
  `TrengerHjelpMed` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ErLivskvalitets` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `VaaknerDuOppFle` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `VaaknerDuMedHod` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `FoelerDuDegUthv` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ErDuTroettPaaDa` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `OppleverDuAande` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `EpworthSleepine` tinyint(3) DEFAULT NULL,
  `Oksygen` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Fukter` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Reserverespirat` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Sug` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Slimmobiliseren` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Pulsoksymeter` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Sondemat` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Boligform` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PasientensArbei` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `UloennedePaaroe` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `LoennedePaaroer` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `BrukerstyrtPers` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `ServiceboligMed` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Team` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Hjemmesykepleie` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Ingen` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Internkommentar` varchar(2000) COLLATE utf8_danish_ci DEFAULT NULL,
  `C_FID` int(10) unsigned DEFAULT NULL,
  `C_CENTREID` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `C_RHF` tinyint(3) DEFAULT NULL,
  `C_REGION` varchar(40) COLLATE utf8_danish_ci DEFAULT NULL,
  `C_CENTRE` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `C_CENTRENAME` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `C_MOVE_TO_HOSPITAL` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `C_HOSPITAL_DEPARTMENT` tinyint(3) DEFAULT NULL,
  `C_STOPDATE` date DEFAULT NULL,
  `C_STOPDATE_MISS` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `C_STOP_CAUSE` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `C_STILL_ALIVE` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `C_DEATH_CAUSE` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `C_DECEASED_DATE` date DEFAULT NULL,
  `C_DECEASED_DATE_MISS` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `C_STATUS` tinyint(3) DEFAULT NULL,
  `CHAIN_IS_STOPPED` int(11) DEFAULT NULL,
  `CHAIN_IS_CONCLUDED` int(11) DEFAULT NULL,
  `CHAIN_BASEREG_STATUS` varchar(2) COLLATE utf8_danish_ci DEFAULT NULL,
  `FerdigstilleSkj` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  PRIMARY KEY (`ForlopsID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `alleVarNum`;
CREATE TABLE `alleVarNum` (
  `AvdRESH` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `SykehusNavn` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ForlopsID` int(9) NOT NULL,
  `PasientID` int(10) unsigned DEFAULT NULL,
  `DatoForInnhenti` date DEFAULT NULL,
  `P_LAST_FREG_DATE` date DEFAULT NULL,
  `P_REGDATE` date DEFAULT NULL,
  `OpprettetAv` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `SistOppdatertAv` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `P_SSN` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `P_SSNTYPE` tinyint(3) DEFAULT NULL,
  `P_SSNSUBTYPE` tinyint(3) DEFAULT NULL,
  `Kjoenn` tinyint(3) DEFAULT NULL,
  `PasientAlder` bigint(20) DEFAULT NULL,
  `PostNr` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `Poststed` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `Kommune` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `KomunneNr` varchar(4) COLLATE utf8_danish_ci DEFAULT NULL,
  `FylkeNr` char(2) COLLATE utf8_danish_ci DEFAULT NULL,
  `Fylke` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `Avdoed` tinyint(3) DEFAULT NULL,
  `Doedsdato` date DEFAULT NULL,
  `R_MCETYPE` tinyint(3) DEFAULT NULL,
  `Historisk` tinyint(3) DEFAULT NULL,
  `Behandlingsstar` date DEFAULT NULL,
  `RegionaltHelsef` tinyint(3) DEFAULT NULL,
  `Helsef` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `Sykehus` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `Avdeling` tinyint(3) DEFAULT NULL,
  `ArteriellPO2KPa` decimal(3,1) DEFAULT NULL,
  `ArteriellPCO2KP` decimal(3,1) DEFAULT NULL,
  `ArteriellSPCO2KP` decimal(3,1) DEFAULT NULL,
  `NattligHypovent` tinyint(3) DEFAULT NULL,
  `AndelAvNattenM` decimal(4,1) DEFAULT NULL,
  `NattligOksygenm` tinyint(3) DEFAULT NULL,
  `ProsentAvTiden` decimal(4,1) DEFAULT NULL,
  `R_SPO2_UNDER90` decimal(4,1) DEFAULT NULL,
  `KapillaerPO2Vaa` decimal(3,1) DEFAULT NULL,
  `KapillaerPCO2Va` decimal(3,1) DEFAULT NULL,
  `BaseExcessMmolL` decimal(3,1) DEFAULT NULL,
  `BaseExcessKapil` decimal(3,1) DEFAULT NULL,
  `VitalkapasitetS` decimal(3,2) DEFAULT NULL,
  `VitalkapasitetL` decimal(3,2) DEFAULT NULL,
  `FVKLiter` decimal(3,2) DEFAULT NULL,
  `FEV1LiterSek` decimal(3,2) DEFAULT NULL,
  `PEFcHostePEFLit` smallint(6) DEFAULT NULL,
  `HoeydeCm` smallint(6) DEFAULT NULL,
  `VektKg` decimal(4,1) DEFAULT NULL,
  `BMI` decimal(16,5) DEFAULT NULL,
  `ForsertVitalkap` decimal(4,1) DEFAULT NULL,
  `FEV1IProsentAvF` decimal(4,1) DEFAULT NULL,
  `R_DIAGNOSIS1` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `HovedDiag` varchar(150) COLLATE utf8_danish_ci DEFAULT NULL,
  `R_DIAGNOSIS1_OTHER` varchar(150) COLLATE utf8_danish_ci DEFAULT NULL,
  `R_DIAGNOSIS2` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `BiDiag` varchar(150) COLLATE utf8_danish_ci DEFAULT NULL,
  `R_DIAGNOSIS2_OTHER` varchar(150) COLLATE utf8_danish_ci DEFAULT NULL,
  `MorgenHodepine` tinyint(3) DEFAULT NULL,
  `Soevnvansker` tinyint(3) DEFAULT NULL,
  `SvekketHostekra` tinyint(3) DEFAULT NULL,
  `Dagtidstretthet` tinyint(3) DEFAULT NULL,
  `Dyspne` tinyint(3) DEFAULT NULL,
  `RegOppstart` tinyint(3) DEFAULT NULL,
  `AntallDagerPaaS` smallint(6) DEFAULT NULL,
  `OmstendigheterV` tinyint(3) DEFAULT NULL,
  `BehandlingstidP` tinyint(3) DEFAULT NULL,
  `Behandlingsmeto` tinyint(3) DEFAULT NULL,
  `Frenikusstimula` tinyint(3) DEFAULT NULL,
  `Respiratortilsl` tinyint(3) DEFAULT NULL,
  `DatoForTrakeost` date DEFAULT NULL,
  `TrengerHjelpMed` tinyint(3) DEFAULT NULL,
  `ErLivskvalitets` tinyint(3) DEFAULT NULL,
  `VaaknerDuOppFle` tinyint(3) DEFAULT NULL,
  `VaaknerDuMedHod` tinyint(3) DEFAULT NULL,
  `FoelerDuDegUthv` tinyint(3) DEFAULT NULL,
  `ErDuTroettPaaDa` tinyint(3) DEFAULT NULL,
  `OppleverDuAande` tinyint(3) DEFAULT NULL,
  `EpworthSleepine` tinyint(3) DEFAULT NULL,
  `Oksygen` tinyint(3) DEFAULT NULL,
  `Fukter` tinyint(3) DEFAULT NULL,
  `Reserverespirat` tinyint(3) DEFAULT NULL,
  `Sug` tinyint(3) DEFAULT NULL,
  `Slimmobiliseren` tinyint(3) DEFAULT NULL,
  `Pulsoksymeter` tinyint(3) DEFAULT NULL,
  `Sondemat` tinyint(3) DEFAULT NULL,
  `Boligform` tinyint(3) DEFAULT NULL,
  `PasientensArbei` tinyint(3) DEFAULT NULL,
  `UloennedePaaroe` tinyint(3) DEFAULT NULL,
  `LoennedePaaroer` tinyint(3) DEFAULT NULL,
  `BrukerstyrtPers` tinyint(3) DEFAULT NULL,
  `ServiceboligMed` tinyint(3) DEFAULT NULL,
  `Team` tinyint(3) DEFAULT NULL,
  `Hjemmesykepleie` tinyint(3) DEFAULT NULL,
  `Ingen` tinyint(3) DEFAULT NULL,
  `RegStatus` tinyint(3) DEFAULT NULL,
  `C_REGION` varchar(40) COLLATE utf8_danish_ci DEFAULT NULL,
  `C_FID` int(10) unsigned DEFAULT NULL,
  `C_CENTREID` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `C_RHF` tinyint(3) DEFAULT NULL,
  `C_CENTRE` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `C_CENTRENAME` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `C_STOPDATE` date DEFAULT NULL,
  `C_STOPDATE_MISS` tinyint(3) DEFAULT NULL,
  `C_STOP_CAUSE` tinyint(3) DEFAULT NULL,
  `C_STILL_ALIVE` tinyint(3) DEFAULT NULL,
  `C_DEATH_CAUSE` tinyint(3) DEFAULT NULL,
  `C_DECEASED_DATE` date DEFAULT NULL,
  `C_STATUS` tinyint(3) DEFAULT NULL,
  `CHAIN_IS_STOPPED` int(11) DEFAULT NULL,
  `CHAIN_IS_CONCLUDED` int(11) DEFAULT NULL,
  `CHAIN_BASEREG_STATUS` varchar(2) COLLATE utf8_danish_ci DEFAULT NULL,
  PRIMARY KEY (`ForlopsID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `all_variables`;
CREATE TABLE `all_variables` (
  `PATIENTID` varchar(10) NOT NULL DEFAULT '0',
  `SSN` varchar(30) DEFAULT NULL,
  `SSNTYPE` varchar(3) DEFAULT NULL,
  `GENDER` varchar(3) DEFAULT NULL,
  `FIRSTNAME` varchar(60) DEFAULT NULL,
  `LASTNAME` varchar(60) DEFAULT NULL,
  `DATEOFBIRTH` date DEFAULT NULL,
  `AGE` bigint(19) DEFAULT NULL,
  `ADDRESS` varchar(100) DEFAULT NULL,
  `ZIPCODE` varchar(30) DEFAULT NULL,
  `CITY` varchar(50) DEFAULT NULL,
  `DECEASED` tinyint(3) DEFAULT NULL,
  `DATEOFDEATH` date DEFAULT NULL,
  `PAT_CREATEDBY` varchar(30) DEFAULT NULL,
  `PAT_UPDATEDBY` varchar(30) DEFAULT NULL,
  `MCEID` varchar(10) NOT NULL DEFAULT '0',
  `MCE_CREATEDBY` varchar(30) DEFAULT NULL,
  `MCE_UPDATEDBY` varchar(30) DEFAULT NULL,
  `REG_MCEID` varchar(10) NOT NULL DEFAULT '0',
  `REG_CENTREID` varchar(30) DEFAULT NULL,
  `Sykehusnavn` varchar(100) DEFAULT NULL,
  `REG_PHYSICIAN` varchar(10) DEFAULT NULL,
  `REG_NURSE` varchar(10) DEFAULT NULL,
  `REG_START_DATE` date DEFAULT NULL,
  `REG_MOVE_TO_RHF` varchar(3) DEFAULT NULL,
  `REG_MOVE_TO_CENTRE` varchar(30) DEFAULT NULL,
  `REG_PO2_AIR` decimal(3,1) DEFAULT NULL,
  `REG_PO2_AIR_MISS` varchar(3) DEFAULT NULL,
  `REG_PCO2_AIR` decimal(3,1) DEFAULT NULL,
  `REG_PCO2_AIR_MISS` varchar(3) DEFAULT NULL,
  `REG_ARTERIALPCO2_AIR` decimal(3,1) DEFAULT NULL,
  `REG_ARTERIALPCO2_AIR_MISS` tinyint(3) DEFAULT NULL,
  `REG_HYPOVENTILATION` tinyint(3) DEFAULT NULL,
  `REG_HYPOVENTILATION_PERCENT` decimal(4,1) DEFAULT NULL,
  `REG_HYPOVENTILATION_PERCENT_MISS` tinyint(3) DEFAULT NULL,
  `REG_OXY_MEASUREMENT` tinyint(3) DEFAULT NULL,
  `REG_SPO2_AVG_PERCENT` decimal(4,1) DEFAULT NULL,
  `SPO2_AVG_PERCENT_MISS` tinyint(3) DEFAULT NULL,
  `REG_HYPO_PERCENT_OF_NIGHT` decimal(4,1) DEFAULT NULL,
  `REG_HYPO_PERCENT_OF_NIGHT_MISS` tinyint(3) DEFAULT NULL,
  `REG_CAPILLARYPO2_AIR` decimal(3,1) DEFAULT NULL,
  `REG_CAPILLARYPO2_AIR_MISS` tinyint(3) DEFAULT NULL,
  `REG_CAPILLARYPCO2_AIR` decimal(3,1) DEFAULT NULL,
  `REG_CAPILLARYPCO2_AIR_MISS` tinyint(3) DEFAULT NULL,
  `REG_BE` decimal(3,1) DEFAULT NULL,
  `REG_BE_MISS` tinyint(3) DEFAULT NULL,
  `REG_VC` decimal(2,1) DEFAULT NULL,
  `REG_VC_MISS` tinyint(3) DEFAULT NULL,
  `REG_VC_LYING` decimal(2,1) DEFAULT NULL,
  `REG_VC_LYING_MISS` tinyint(3) DEFAULT NULL,
  `REG_VC_SUPINE` decimal(2,1) DEFAULT NULL,
  `REG_VC_SUPINE_MISS` tinyint(3) DEFAULT NULL,
  `REG_FEV1` decimal(2,1) DEFAULT NULL,
  `REG_FEV1_MISS` tinyint(3) DEFAULT NULL,
  `REG_HOSTEPEF` smallint(5) DEFAULT NULL,
  `REG_HOSTEPEF_MISS` tinyint(3) DEFAULT NULL,
  `REG_HEIGHT` smallint(5) DEFAULT NULL,
  `REG_HEIGHT_MISS` tinyint(3) DEFAULT NULL,
  `REG_WEIGHT` smallint(5) DEFAULT NULL,
  `REG_WEIGHT_MISS` tinyint(3) DEFAULT NULL,
  `REG_VC_PERCENT_PREDICTED` varchar(30) DEFAULT NULL,
  `REG_FEV1_PERCENT_PREDICTED` varchar(30) DEFAULT NULL,
  `REG_DIAGNOSIS1` tinyint(3) DEFAULT NULL,
  `REG_MAINDIAGNOSIS` varchar(2000) DEFAULT NULL,
  `REG_DIAGNOSIS1_OTHER_SPECIFY` varchar(150) DEFAULT NULL,
  `REG_DIAGNOSIS2` tinyint(3) DEFAULT NULL,
  `REG_BIDIAGNOSIS` varchar(2000) DEFAULT NULL,
  `REG_DIAGNOSIS2_OTHER_SPECIFY` varchar(150) DEFAULT NULL,
  `REG_SYMPTOM_HEADACHE` tinyint(3) DEFAULT NULL,
  `REG_SYMPTOM_INSOMNIA` tinyint(3) DEFAULT NULL,
  `REG_SYMPTOM_INFECTION_ETC` tinyint(3) DEFAULT NULL,
  `REG_SYMPTOM_FATIGUE` tinyint(3) DEFAULT NULL,
  `REG_SYMPTOM_DYSPNEA` tinyint(3) DEFAULT NULL,
  `REG_STARTUP` tinyint(3) DEFAULT NULL,
  `REG_HOSPITAL_DAYS_DISCHARGE` smallint(5) DEFAULT NULL,
  `REG_SITUATION_VENTILATION` tinyint(3) DEFAULT NULL,
  `REG_VENTILATION_HOURS` tinyint(3) DEFAULT NULL,
  `REG_VENTILATION_METHOD` tinyint(3) DEFAULT NULL,
  `REG_CONNECTION` varchar(2000) DEFAULT NULL,
  `REG_TREATMENT` varchar(2000) DEFAULT NULL,
  `REG_RESPCON` tinyint(3) DEFAULT NULL,
  `REG_VENTILATION_ASSISTANCE` tinyint(3) DEFAULT NULL,
  `REG_QUALITYOFLIFE` tinyint(3) DEFAULT NULL,
  `REG_QLWAKEUP` tinyint(3) DEFAULT NULL,
  `REG_QLHEADACHE` tinyint(3) DEFAULT NULL,
  `REG_QLRESTED` tinyint(3) DEFAULT NULL,
  `REG_QLSLEEPY` tinyint(3) DEFAULT NULL,
  `REG_QLDYSPNOEA` tinyint(3) DEFAULT NULL,
  `REG_QLESS` tinyint(3) DEFAULT NULL,
  `REG_ADDITIONAL_OXYGEN` tinyint(3) DEFAULT NULL,
  `REG_ADDITIONAL_HUMIDIFIER` tinyint(3) DEFAULT NULL,
  `REG_ADDITIONAL_SPARE_RESP` tinyint(3) DEFAULT NULL,
  `REG_ADDITIONAL_SUCTION` tinyint(3) DEFAULT NULL,
  `REG_ADDITIONAL_COUGH_MACHINE` tinyint(3) DEFAULT NULL,
  `REG_ADDITIONAL_OXIMETER` tinyint(3) DEFAULT NULL,
  `REG_RESIDENTIAL_FORM` tinyint(3) DEFAULT NULL,
  `REG_WORK_STATUS` tinyint(3) DEFAULT NULL,
  `REG_CARE_SERVICES_UNPAID_RELATIVES` tinyint(3) DEFAULT NULL,
  `REG_CARE_SERVICES_PAID_RELATIVES` tinyint(3) DEFAULT NULL,
  `REG_CARE_SERVICES_USER_PERS_ASSISTANT` tinyint(3) DEFAULT NULL,
  `REG_CARE_SERVICES_SERVICE_HOUSING` tinyint(3) DEFAULT NULL,
  `REG_CARE_SERVICES_TEAM` tinyint(3) DEFAULT NULL,
  `REG_CARE_SERVICES_HOME_NURSING` tinyint(3) DEFAULT NULL,
  `REG_CARE_SERVICES_UNKNOWN` tinyint(3) DEFAULT NULL,
  `REG_COMMENTS` varchar(300) DEFAULT NULL,
  `REG_USERCOMMENT` varchar(2000) DEFAULT NULL,
  `REG_STATUS` tinyint(3) DEFAULT NULL,
  `REG_TSUPDATED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `REG_UPDATEDBY` varchar(30) DEFAULT NULL,
  `REG_TSCREATED` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `REG_CREATEDBY` varchar(30) DEFAULT NULL,
  `FOL1_FID` bigint(10) NOT NULL DEFAULT '0',
  `FOL1_CENTREID` varchar(30) DEFAULT NULL,
  `FOL1_MCEID` bigint(10) DEFAULT NULL,
  `FOL1_YEAR` tinyint(3) DEFAULT NULL,
  `FOL1PHYSICIAN` int(10) DEFAULT NULL,
  `FOL1_NURSE` int(10) DEFAULT NULL,
  `FOL1_MOVE_TO_RHF` tinyint(3) DEFAULT NULL,
  `FOL1_TO_CENTRE` varchar(30) DEFAULT NULL,
  `FOL1_PO2AIR` decimal(3,1) DEFAULT NULL,
  `FOL1_PO2_AIR_MISS` tinyint(3) DEFAULT NULL,
  `FOL1_PCO2_AIR` decimal(3,1) DEFAULT NULL,
  `FOL1_PCO2_AIR_MISS` tinyint(3) DEFAULT NULL,
  `FOL1_ARTERIALPCO2_AIR` decimal(3,1) DEFAULT NULL,
  `FOL1_ARTERIALPCO2_AIR_MISS` tinyint(3) DEFAULT NULL,
  `FOL1_HYPOVENTILATION` tinyint(3) DEFAULT NULL,
  `FOL1_HYPOVENTILATION_PERCENT` decimal(4,1) DEFAULT NULL,
  `FOL1_HYPOVENTILATION_PERCENT_MISS` tinyint(3) DEFAULT NULL,
  `FOL1_OXY_MEASUREMEMT` tinyint(3) DEFAULT NULL,
  `FOL1_SPO2_AVG_PERCENT` decimal(4,1) DEFAULT NULL,
  `FOL1_SPO2_AVG_PERCENT_MISS` tinyint(3) DEFAULT NULL,
  `FOL1_HYPO_PERCENT_OF_NIGHT` decimal(4,1) DEFAULT NULL,
  `FOL1_HYPO_PERCENT_OF_NIGHT_MISS` tinyint(3) DEFAULT NULL,
  `FOL1_CAPILLARYPO2_AIR` decimal(3,1) DEFAULT NULL,
  `FOL1_CAPILLARYPO2_AIR_MISS` tinyint(3) DEFAULT NULL,
  `FOL1_CAPILLARYPCO2_AIR` decimal(3,1) DEFAULT NULL,
  `FOL1_CAPILLARYPCO2_AIR_MISS` tinyint(3) DEFAULT NULL,
  `FOL1_BE` decimal(3,1) DEFAULT NULL,
  `FOL1_BE_MISS` tinyint(3) DEFAULT NULL,
  `FOL1_VC` decimal(2,1) DEFAULT NULL,
  `FOL1_VC_MISS` tinyint(3) DEFAULT NULL,
  `FOL1_VC_LYING` decimal(2,1) DEFAULT NULL,
  `FOL1_VC_LYING_MISS` tinyint(3) DEFAULT NULL,
  `FOL1_VC_SUPINE` decimal(2,1) DEFAULT NULL,
  `FOL1_VC_SUPINE_MISS` tinyint(3) DEFAULT NULL,
  `FOL1_FEV1` decimal(2,1) DEFAULT NULL,
  `FOL1_FEV1_MISS` tinyint(3) DEFAULT NULL,
  `FOL1_HOSTEPEF` smallint(5) DEFAULT NULL,
  `FOL1_HOSTEPEF_MISS` tinyint(3) DEFAULT NULL,
  `FOL1_HEIGHT` smallint(5) DEFAULT NULL,
  `FOL1_HEIGHT_MISS` tinyint(3) DEFAULT NULL,
  `FOL1_WEIGHT` smallint(5) DEFAULT NULL,
  `FOL1_WEIGHT_MISS` tinyint(3) DEFAULT NULL,
  `FOL1_VC_PERCENT_PREDICTED` varchar(30) DEFAULT NULL,
  `FOL1_EV1_PERCENT_PREDICTED` varchar(30) DEFAULT NULL,
  `FOL1_VENTILATION_HOURS` tinyint(3) DEFAULT NULL,
  `FOL1_VENTILATION_METHOD` tinyint(3) DEFAULT NULL,
  `FOL1_RESPCON` tinyint(3) DEFAULT NULL,
  `FOL1_VENTILATION_ASSISTANCE` tinyint(3) DEFAULT NULL,
  `FOL1_FOLLOWUP_DATE` date DEFAULT NULL,
  `FOL1_STOP` tinyint(3) DEFAULT NULL,
  `FOL1_QUALITYOFLIFE` tinyint(3) DEFAULT NULL,
  `FOL1_QLWAKEUP` tinyint(3) DEFAULT NULL,
  `FOL1_QLHEADACHE` tinyint(3) DEFAULT NULL,
  `FOL1_QLRESTED` tinyint(3) DEFAULT NULL,
  `FOL1_QLSLEEPY` tinyint(3) DEFAULT NULL,
  `FOL1_QLDYSPNOEA` tinyint(3) DEFAULT NULL,
  `FOL1_QLESS` tinyint(3) DEFAULT NULL,
  `FOL1_ADDITIONAL_OXYGEN` tinyint(3) DEFAULT NULL,
  `FOL1_ADDITIONAL_HUMIDIFIER` tinyint(3) DEFAULT NULL,
  `FOL_1ADDITIONAL_SPARE_RESP` tinyint(3) DEFAULT NULL,
  `FOL1_ADDITIONAL_SUCTION` tinyint(3) DEFAULT NULL,
  `FOL1_ADDITIONAL_COUGH_MACHINE` tinyint(3) DEFAULT NULL,
  `FOL1_ADDITIONAL_OXIMETER` tinyint(3) DEFAULT NULL,
  `FOL1_RESIDENTIAL_FORM` tinyint(3) DEFAULT NULL,
  `FOL1_WORK_STATUS` tinyint(3) DEFAULT NULL,
  `FOL1_CARE_SERVICES_UNPAID_RELATIVES` tinyint(3) DEFAULT NULL,
  `FOL1_CARE_SERVICES_PAID_RELATIVES` tinyint(3) DEFAULT NULL,
  `FOL1_CARE_SERVICES_USER_PERS_ASSISTANT` tinyint(3) DEFAULT NULL,
  `FOL1_CARE_SERVICES_SERVICE_HOUSING` tinyint(3) DEFAULT NULL,
  `FOL1_CARE_SERVICES_TEAM` tinyint(3) DEFAULT NULL,
  `FOL1_CARE_SERVICES_HOME_NURSING` tinyint(3) DEFAULT NULL,
  `FOL1_CARE_SERVICES_UNKNOWN` tinyint(3) DEFAULT NULL,
  `FOL1_COMMENTS` varchar(300) DEFAULT NULL,
  `FOL1_USERCOMMENT` varchar(2000) DEFAULT NULL,
  `FOL1_STATUS` tinyint(3) DEFAULT NULL,
  `FOL1_TSUPDATED` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `FOL1_UPDATEDBY` varchar(30) DEFAULT NULL,
  `FOL1_TSCREATED` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `FOL1_CREATEDBY` varchar(30) DEFAULT NULL,
  `FOL3_FID` bigint(10) NOT NULL DEFAULT '0',
  `FOL3_CENTREID` varchar(30) DEFAULT NULL,
  `FOL3_MCEID` bigint(10) DEFAULT NULL,
  `FOL3_YEAR` tinyint(3) DEFAULT NULL,
  `FOL3PHYSICIAN` int(10) DEFAULT NULL,
  `FOL3_NURSE` int(10) DEFAULT NULL,
  `FOL3_MOVE_TO_RHF` tinyint(3) DEFAULT NULL,
  `FOL3_TO_CENTRE` varchar(30) DEFAULT NULL,
  `FOL3_PO2AIR` decimal(3,1) DEFAULT NULL,
  `FOL3_PO2_AIR_MISS` tinyint(3) DEFAULT NULL,
  `FOL3_PCO2_AIR` decimal(3,1) DEFAULT NULL,
  `FOL3_PCO2_AIR_MISS` tinyint(3) DEFAULT NULL,
  `FOL3_ARTERIALPCO2_AIR` decimal(3,1) DEFAULT NULL,
  `FOL3_ARTERIALPCO2_AIR_MISS` tinyint(3) DEFAULT NULL,
  `FOL3_HYPOVENTILATION` tinyint(3) DEFAULT NULL,
  `FOL3_HYPOVENTILATION_PERCENT` decimal(4,1) DEFAULT NULL,
  `FOL3_HYPOVENTILATION_PERCENT_MISS` tinyint(3) DEFAULT NULL,
  `FOL3_OXY_MEASUREMEMT` tinyint(3) DEFAULT NULL,
  `FOL3_SPO2_AVG_PERCENT` decimal(4,1) DEFAULT NULL,
  `FOL3_SPO2_AVG_PERCENT_MISS` tinyint(3) DEFAULT NULL,
  `FOL3_HYPO_PERCENT_OF_NIGHT` decimal(4,1) DEFAULT NULL,
  `FOL3_HYPO_PERCENT_OF_NIGHT_MISS` tinyint(3) DEFAULT NULL,
  `FOL3_CAPILLARYPO2_AIR` decimal(3,1) DEFAULT NULL,
  `FOL3_CAPILLARYPO2_AIR_MISS` tinyint(3) DEFAULT NULL,
  `FOL3_CAPILLARYPCO2_AIR` decimal(3,1) DEFAULT NULL,
  `FOL3_CAPILLARYPCO2_AIR_MISS` tinyint(3) DEFAULT NULL,
  `FOL3_BE` decimal(3,1) DEFAULT NULL,
  `FOL3_BE_MISS` tinyint(3) DEFAULT NULL,
  `FOL3_VC` decimal(2,1) DEFAULT NULL,
  `FOL3_VC_MISS` tinyint(3) DEFAULT NULL,
  `FOL3_VC_LYING` decimal(2,1) DEFAULT NULL,
  `FOL3_VC_LYING_MISS` tinyint(3) DEFAULT NULL,
  `FOL3_VC_SUPINE` decimal(2,1) DEFAULT NULL,
  `FOL3_VC_SUPINE_MISS` tinyint(3) DEFAULT NULL,
  `FOL3_FEV1` decimal(2,1) DEFAULT NULL,
  `FOL3_FEV1_MISS` tinyint(3) DEFAULT NULL,
  `FOL3_HOSTEPEF` smallint(5) DEFAULT NULL,
  `FOL3_HOSTEPEF_MISS` tinyint(3) DEFAULT NULL,
  `FOL3_HEIGHT` smallint(5) DEFAULT NULL,
  `FOL3_HEIGHT_MISS` tinyint(3) DEFAULT NULL,
  `FOL3_WEIGHT` smallint(5) DEFAULT NULL,
  `FOL3_WEIGHT_MISS` tinyint(3) DEFAULT NULL,
  `FOL3_VC_PERCENT_PREDICTED` varchar(30) DEFAULT NULL,
  `FOL3_EV1_PERCENT_PREDICTED` varchar(30) DEFAULT NULL,
  `FOL3_VENTILATION_HOURS` tinyint(3) DEFAULT NULL,
  `FOL3_VENTILATION_METHOD` tinyint(3) DEFAULT NULL,
  `FOL3_RESPCON` tinyint(3) DEFAULT NULL,
  `FOL3_VENTILATION_ASSISTANCE` tinyint(3) DEFAULT NULL,
  `FOL3_FOLLOWUP_DATE` date DEFAULT NULL,
  `FOL3_STOP` tinyint(3) DEFAULT NULL,
  `FOL3_QUALITYOFLIFE` tinyint(3) DEFAULT NULL,
  `FOL3_QLWAKEUP` tinyint(3) DEFAULT NULL,
  `FOL3_QLHEADACHE` tinyint(3) DEFAULT NULL,
  `FOL3_QLRESTED` tinyint(3) DEFAULT NULL,
  `FOL3_QLSLEEPY` tinyint(3) DEFAULT NULL,
  `FOL3_QLDYSPNOEA` tinyint(3) DEFAULT NULL,
  `FOL3_QLESS` tinyint(3) DEFAULT NULL,
  `FOL3_ADDITIONAL_OXYGEN` tinyint(3) DEFAULT NULL,
  `FOL3_ADDITIONAL_HUMIDIFIER` tinyint(3) DEFAULT NULL,
  `FOL_3ADDITIONAL_SPARE_RESP` tinyint(3) DEFAULT NULL,
  `FOL3_ADDITIONAL_SUCTION` tinyint(3) DEFAULT NULL,
  `FOL3_ADDITIONAL_COUGH_MACHINE` tinyint(3) DEFAULT NULL,
  `FOL3_ADDITIONAL_OXIMETER` tinyint(3) DEFAULT NULL,
  `FOL3_RESIDENTIAL_FORM` tinyint(3) DEFAULT NULL,
  `FOL3_WORK_STATUS` tinyint(3) DEFAULT NULL,
  `FOL3_CARE_SERVICES_UNPAID_RELATIVES` tinyint(3) DEFAULT NULL,
  `FOL3_CARE_SERVICES_PAID_RELATIVES` tinyint(3) DEFAULT NULL,
  `FOL3_CARE_SERVICES_USER_PERS_ASSISTANT` tinyint(3) DEFAULT NULL,
  `FOL3_CARE_SERVICES_SERVICE_HOUSING` tinyint(3) DEFAULT NULL,
  `FOL3_CARE_SERVICES_TEAM` tinyint(3) DEFAULT NULL,
  `FOL3_CARE_SERVICES_HOME_NURSING` tinyint(3) DEFAULT NULL,
  `FOL3_CARE_SERVICES_UNKNOWN` tinyint(3) DEFAULT NULL,
  `FOL3_COMMENTS` varchar(300) DEFAULT NULL,
  `FOL3_USERCOMMENT` varchar(2000) DEFAULT NULL,
  `FOL3_STATUS` tinyint(3) DEFAULT NULL,
  `FOL3_TSUPDATED` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `FOL3_UPDATEDBY` varchar(30) DEFAULT NULL,
  `FOL3_TSCREATED` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `FOL3_CREATEDBY` varchar(30) DEFAULT NULL,
  `CONC_MCEID` bigint(10) NOT NULL DEFAULT '0',
  `CONC_CENTREID` varchar(30) DEFAULT NULL,
  `CONC_MOVE_TO_RHF` tinyint(3) DEFAULT NULL,
  `CONC_MOVE_TO_CENTRE` varchar(30) DEFAULT NULL,
  `CONC_STOP_DATE` date DEFAULT NULL,
  `CONC_STOP_DATE_MISS` tinyint(3) DEFAULT NULL,
  `CONC_STOP_CAUSE` tinyint(3) DEFAULT NULL,
  `CONC_STILL_ALIVE` tinyint(3) DEFAULT NULL,
  `CONC_STOP_DEATH` tinyint(3) DEFAULT NULL,
  `CONC_DECEASED_DATE` date DEFAULT NULL,
  `CONC_DECEASED_DATE_MISS` tinyint(3) DEFAULT NULL,
  `CONC_TREATMENTDAYS` smallint(5) DEFAULT NULL,
  `CONC_USERCOMMENT` varchar(2000) DEFAULT NULL,
  `CONC_STATUS` tinyint(3) DEFAULT NULL,
  `CONC_TSUPDATED` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `CONC_UPDATEDBY` varchar(30) DEFAULT NULL,
  `CONC_TSCREATED` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `CONC_CREATEDBY` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`MCEID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `centre`;
CREATE TABLE `centre` (
  `ID` varchar(30) COLLATE utf8_danish_ci NOT NULL,
  `CENTRENAME` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BELONGSTO` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `ORGANISATION` varchar(11) COLLATE utf8_danish_ci DEFAULT NULL,
  `CENTRESHORTNAME` varchar(10) COLLATE utf8_danish_ci DEFAULT NULL,
  `TIMEZONE` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `IMPORTFORMAT` int(11) DEFAULT NULL,
  `IMPORTING` tinyint(3) DEFAULT NULL,
  `STATUS` tinyint(3) DEFAULT NULL,
  `LANGUAGEID` char(2) COLLATE utf8_danish_ci DEFAULT NULL,
  `COUNTRYID` char(2) COLLATE utf8_danish_ci DEFAULT NULL,
  `TYPEID` int(11) DEFAULT NULL,
  `TEST` tinyint(3) DEFAULT NULL,
  `DEFAULTLANGUAGEID` char(2) COLLATE utf8_danish_ci DEFAULT NULL,
  `CREATEDBY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `TSCREATED` timestamp NULL DEFAULT NULL,
  `UPDATEDBY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `TSUPDATED` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `centretype`;
CREATE TABLE `centretype` (
  `ID` int(10) NOT NULL,
  `NAME` varchar(40) COLLATE utf8_danish_ci DEFAULT NULL,
  `STATUS` tinyint(3) DEFAULT NULL,
  `TSCREATED` timestamp NULL DEFAULT NULL,
  `TSUPDATED` timestamp NULL DEFAULT NULL,
  `CREATEDBY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `UPDATEDBY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `chainview`;
CREATE TABLE `chainview` (
  `PID` int(9) NOT NULL,
  `DECEASED_DATE` date DEFAULT NULL,
  `BASE_REG_CENTRE` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `SykehusNavn` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BASE_ID` int(9) NOT NULL,
  `VENTREG_STATUS` tinyint(3) DEFAULT NULL,
  `REGISTRATION_DATE` date DEFAULT NULL,
  `CONCLUDE_DATE` date DEFAULT NULL,
  `CONCLUDE_STATUS` tinyint(3) DEFAULT NULL,
  `NEXT_FOLLOUP_CENTRE` text COLLATE utf8_danish_ci,
  `NEXT_FOLLOUP_YEAR` tinyint(3) DEFAULT NULL,
  `NEXT_FOLLOWUP_DATE` date DEFAULT NULL,
  `FOLLOWING_UP` tinyint(3) DEFAULT NULL,
  `HAS_CONCLUDE` tinyint(3) DEFAULT NULL,
  `IS_STOPPED` int(11) DEFAULT NULL,
  `BasisKjedeStatus` varchar(2) COLLATE utf8_danish_ci DEFAULT NULL,
  `IS_CONCLUDED` int(11) DEFAULT NULL,
  `STOPPED_YEAR` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `change_log_variables`;
CREATE TABLE `change_log_variables` (
  `tablename` varchar(255) COLLATE utf8_danish_ci DEFAULT NULL,
  `columnname` varchar(255) COLLATE utf8_danish_ci DEFAULT NULL,
  `diffstatus` varchar(255) COLLATE utf8_danish_ci DEFAULT NULL,
  `database_name` varchar(255) COLLATE utf8_danish_ci DEFAULT NULL,
  `type` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `size` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `logdate` datetime DEFAULT NULL,
  `version` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `srcenvironment` varchar(255) COLLATE utf8_danish_ci DEFAULT NULL,
  `trgenvironment` varchar(255) COLLATE utf8_danish_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `conclude`;
CREATE TABLE `conclude` (
  `MCEID` int(9) NOT NULL,
  `CENTREID` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `MOVE_TO_RHF` tinyint(3) DEFAULT NULL,
  `MOVE_TO_CENTRE` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `MOVE_TO_HOSPITAL` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `HOSPITAL_DEPARTMENT` tinyint(3) DEFAULT NULL,
  `STOP_DATE` date DEFAULT NULL,
  `STOP_DATE_MISS` tinyint(3) DEFAULT NULL,
  `STOP_CAUSE` tinyint(3) DEFAULT NULL,
  `STILL_ALIVE` tinyint(3) DEFAULT NULL,
  `STOP_DEATH` tinyint(3) DEFAULT NULL,
  `DECEASED_DATE` date DEFAULT NULL,
  `DECEASED_DATE_MISS` tinyint(3) DEFAULT NULL,
  `USERCOMMENT` varchar(2000) COLLATE utf8_danish_ci DEFAULT NULL,
  `STATUS` tinyint(3) DEFAULT NULL,
  `TSUPDATED` timestamp NULL DEFAULT NULL,
  `UPDATEDBY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `FIRST_TIME_CLOSED` timestamp NULL DEFAULT NULL,
  `FIRST_TIME_CLOSED_BY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `TSCREATED` timestamp NULL DEFAULT NULL,
  `CREATEDBY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  PRIMARY KEY (`MCEID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `followups`;
CREATE TABLE `followups` (
  `F_FID` int(9) NOT NULL,
  `F_CENTREID` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_PATIENT_ID` int(10) unsigned DEFAULT NULL,
  `F_MCETYPE` varchar(18) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_HISTORICAL` varchar(3) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_PARENT_MCE` int(10) unsigned DEFAULT NULL,
  `F_YEAR` tinyint(3) DEFAULT NULL,
  `F_RHF` tinyint(3) DEFAULT NULL,
  `F_CENTRE` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_CENTRENAME` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_HOSPITAL` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_HOSPITAL_DEPARTMENT` tinyint(3) DEFAULT NULL,
  `F_ART_O2` decimal(3,1) DEFAULT NULL,
  `F_ART_O2_MISS` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_ART_CO2` decimal(3,1) DEFAULT NULL,
  `F_ART_CO2_MISS` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_CO2_SLEEP` decimal(3,1) DEFAULT NULL,
  `F_CO2_SLEEP_MISS` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_HYPOVENT` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_HYPOVENT_PERC` decimal(4,1) DEFAULT NULL,
  `F_HYPOVENT_PERC_MISS` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_OXY_MEASUREMENT` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_SPO2_AVG_PERC` decimal(4,1) DEFAULT NULL,
  `F_SPO2_AVG_PERC_MISS` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_SPO2_UNDER90` decimal(4,1) DEFAULT NULL,
  `F_SPO2_UNDER90_MISS` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_CAP_O2` decimal(3,1) DEFAULT NULL,
  `F_CAP_O2_MISS` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_CAP_CO2` decimal(3,1) DEFAULT NULL,
  `F_CAP_CO2_MISS` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_BE` decimal(3,1) DEFAULT NULL,
  `F_BE_MISS` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_VC_SITTING` decimal(2,1) DEFAULT NULL,
  `F_VC_SITTING_MISS` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_VC_LYING` decimal(2,1) DEFAULT NULL,
  `F_VC_LYING_MISS` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_FVC` decimal(2,1) DEFAULT NULL,
  `F_FVC_MISS` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_FEV1` decimal(2,1) DEFAULT NULL,
  `F_FEV1_MISS` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_COUGHPEF` smallint(6) DEFAULT NULL,
  `F_COUGHPEMISS` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_HEIGHT` smallint(6) DEFAULT NULL,
  `F_HEIGHT_MISS` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_WEIGHT` decimal(4,1) DEFAULT NULL,
  `F_WEIGHT_MISS` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_BMI` decimal(16,5) DEFAULT NULL,
  `F_FVC_PP` decimal(4,1) DEFAULT NULL,
  `F_FEV1_PP` decimal(4,1) DEFAULT NULL,
  `F_VENT_HOURS` tinyint(3) DEFAULT NULL,
  `F_VENT_MACHINE2` tinyint(3) DEFAULT NULL,
  `F_VENT_MACHINE` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_VENT_FRENIKUS2` tinyint(3) DEFAULT NULL,
  `F_VENT_FRENIKUS` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_VENT_CONNECTION2` tinyint(3) DEFAULT NULL,
  `F_VENT_CONNECTION` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_TRACDATE` date DEFAULT NULL,
  `F_VENTASSIST` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_FOLLOWUP_DATE` date DEFAULT NULL,
  `F_STOP` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_QUALITYOFLIFE` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_QL_WAKEUP` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_QL_HEADACHE` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_QL_RESTED` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_QL_SLEEPY` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_QL_DYSPNEA` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_QL_ESS` tinyint(3) DEFAULT NULL,
  `F_ADD_OXYGEN` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_ADD_HUMIDIFIER` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_ADD_SPARE_RESP` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_ADD_SUCTION` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_ADD_COUGHMACHINE` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_ADD_OXIMETER` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_ADD_TUBE_FEEDING` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_RESIDENTIALFORM` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_ZIPCODE` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_TOWN` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_KOMMUNE` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_KOMMUNENR` varchar(4) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_FYLKESNR` varchar(2) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_FYLKE` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_WORKSTATUS` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_CARE_UNPAID_RELATIVES` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_CARE_PAID_RELATIVES` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_CARE_PERS_ASSISTANT` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_CARE_SERVICEHOUSING` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_CARE_TEAM` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_CARE_HOME_NURSING` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_CARE_NONE` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_STATUS` tinyint(3) DEFAULT NULL,
  `CHAIN_IS_STOPPED` int(11) DEFAULT NULL,
  `CHAIN_IS_CONCLUDED` int(11) DEFAULT NULL,
  `CHAIN_BASEREG_STATUS` varchar(2) COLLATE utf8_danish_ci DEFAULT NULL,
  PRIMARY KEY (`F_FID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `followupsNum`;
CREATE TABLE `followupsNum` (
  `F_FID` int(9) NOT NULL,
  `F_CENTREID` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_PATIENT_ID` int(10) unsigned DEFAULT NULL,
  `F_MCETYPE` tinyint(3) DEFAULT NULL,
  `F_HISTORICAL` tinyint(3) DEFAULT NULL,
  `F_PARENT_MCE` int(10) unsigned DEFAULT NULL,
  `F_YEAR` tinyint(3) DEFAULT NULL,
  `F_RHF` tinyint(3) DEFAULT NULL,
  `F_CENTRE` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_CENTRENAME` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_HOSPITAL` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_HOSPITAL_DEPARTMENT` tinyint(3) DEFAULT NULL,
  `F_ART_O2` decimal(3,1) DEFAULT NULL,
  `F_ART_O2_MISS` tinyint(3) DEFAULT NULL,
  `F_ART_CO2` decimal(3,1) DEFAULT NULL,
  `F_ART_CO2_MISS` tinyint(3) DEFAULT NULL,
  `F_CO2_SLEEP` decimal(3,1) DEFAULT NULL,
  `F_CO2_SLEEP_MISS` tinyint(3) DEFAULT NULL,
  `F_HYPOVENT` tinyint(3) DEFAULT NULL,
  `F_HYPOVENT_PERC` decimal(4,1) DEFAULT NULL,
  `F_HYPOVENT_PERC_MISS` tinyint(3) DEFAULT NULL,
  `F_OXY_MEASUREMENT` tinyint(3) DEFAULT NULL,
  `F_SPO2_AVG_PERC` decimal(4,1) DEFAULT NULL,
  `F_SPO2_AVG_PERC_MISS` tinyint(3) DEFAULT NULL,
  `F_SPO2_UNDER90` decimal(4,1) DEFAULT NULL,
  `F_SPO2_UNDER90_MISS` tinyint(3) DEFAULT NULL,
  `F_CAP_O2` decimal(3,1) DEFAULT NULL,
  `F_CAP_O2_MISS` tinyint(3) DEFAULT NULL,
  `F_CAP_CO2` decimal(3,1) DEFAULT NULL,
  `F_CAP_CO2_MISS` tinyint(3) DEFAULT NULL,
  `F_BE` decimal(3,1) DEFAULT NULL,
  `F_BE_MISS` tinyint(3) DEFAULT NULL,
  `F_VC_SITTING` decimal(2,1) DEFAULT NULL,
  `F_VC_SITTING_MISS` tinyint(3) DEFAULT NULL,
  `F_VC_LYING` decimal(2,1) DEFAULT NULL,
  `F_VC_LYING_MISS` tinyint(3) DEFAULT NULL,
  `F_FVC` decimal(2,1) DEFAULT NULL,
  `F_FVC_MISS` tinyint(3) DEFAULT NULL,
  `F_FEV1` decimal(2,1) DEFAULT NULL,
  `F_FEV1_MISS` tinyint(3) DEFAULT NULL,
  `F_COUGHPEF` smallint(6) DEFAULT NULL,
  `F_COUGHPEMISS` tinyint(3) DEFAULT NULL,
  `F_HEIGHT` smallint(6) DEFAULT NULL,
  `F_HEIGHT_MISS` tinyint(3) DEFAULT NULL,
  `F_WEIGHT` decimal(4,1) DEFAULT NULL,
  `F_WEIGHT_MISS` tinyint(3) DEFAULT NULL,
  `F_BMI` decimal(16,5) DEFAULT NULL,
  `F_FVC_PP` decimal(4,1) DEFAULT NULL,
  `F_FEV1_PP` decimal(4,1) DEFAULT NULL,
  `F_VENT_HOURS` tinyint(3) DEFAULT NULL,
  `F_VENT_MACHINE2` tinyint(3) DEFAULT NULL,
  `F_VENT_MACHINE` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_VENT_FRENIKUS2` tinyint(3) DEFAULT NULL,
  `F_VENT_FRENIKUS` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_VENT_CONNECTION2` tinyint(3) DEFAULT NULL,
  `F_VENT_CONNECTION` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_TRACDATE` date DEFAULT NULL,
  `F_VENTASSIST` tinyint(3) DEFAULT NULL,
  `F_FOLLOWUP_DATE` date DEFAULT NULL,
  `F_STOP` tinyint(3) DEFAULT NULL,
  `F_QUALITYOFLIFE` tinyint(3) DEFAULT NULL,
  `F_QL_WAKEUP` tinyint(3) DEFAULT NULL,
  `F_QL_HEADACHE` tinyint(3) DEFAULT NULL,
  `F_QL_RESTED` tinyint(3) DEFAULT NULL,
  `F_QL_SLEEPY` tinyint(3) DEFAULT NULL,
  `F_QL_DYSPNEA` tinyint(3) DEFAULT NULL,
  `F_QL_ESS` tinyint(3) DEFAULT NULL,
  `F_ADD_OXYGEN` tinyint(3) DEFAULT NULL,
  `F_ADD_HUMIDIFIER` tinyint(3) DEFAULT NULL,
  `F_ADD_SPARE_RESP` tinyint(3) DEFAULT NULL,
  `F_ADD_SUCTION` tinyint(3) DEFAULT NULL,
  `F_ADD_COUGHMACHINE` tinyint(3) DEFAULT NULL,
  `F_ADD_OXIMETER` tinyint(3) DEFAULT NULL,
  `F_ADD_TUBE_FEEDING` tinyint(3) DEFAULT NULL,
  `F_RESIDENTIALFORM` tinyint(3) DEFAULT NULL,
  `F_ZIPCODE` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_TOWN` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_KOMMUNE` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_KOMMUNENR` varchar(4) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_FYLKESNR` varchar(2) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_FYLKE` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_WORKSTATUS` tinyint(3) DEFAULT NULL,
  `F_CARE_UNPAID_RELATIVES` tinyint(3) DEFAULT NULL,
  `F_CARE_PAID_RELATIVES` tinyint(3) DEFAULT NULL,
  `F_CARE_PERS_ASSISTANT` tinyint(3) DEFAULT NULL,
  `F_CARE_SERVICEHOUSING` tinyint(3) DEFAULT NULL,
  `F_CARE_TEAM` tinyint(3) DEFAULT NULL,
  `F_CARE_HOME_NURSING` tinyint(3) DEFAULT NULL,
  `F_CARE_NONE` tinyint(3) DEFAULT NULL,
  `F_CREATEDBY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_UPDATEDBY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `F_STATUS` tinyint(3) DEFAULT NULL,
  `CHAIN_IS_STOPPED` int(11) DEFAULT NULL,
  `CHAIN_IS_CONCLUDED` int(11) DEFAULT NULL,
  `CHAIN_BASEREG_STATUS` varchar(2) COLLATE utf8_danish_ci DEFAULT NULL,
  PRIMARY KEY (`F_FID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `ForlopsOversikt`;
CREATE TABLE `ForlopsOversikt` (
  `AvdRESH` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `SykehusNavn` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PasientID` varchar(10) COLLATE utf8_danish_ci DEFAULT NULL,
  `Postnr` varchar(4) COLLATE utf8_danish_ci DEFAULT NULL,
  `PostSted` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `Kommune` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `KommuneNr` varchar(4) COLLATE utf8_danish_ci DEFAULT NULL,
  `Fylke` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `FylkeNr` varchar(2) COLLATE utf8_danish_ci DEFAULT NULL,
  `KryptertFnr` int(10) unsigned DEFAULT NULL,
  `PasientKjonn` varchar(13) COLLATE utf8_danish_ci DEFAULT NULL,
  `erMann` varchar(1) COLLATE utf8_danish_ci DEFAULT NULL,
  `PasientAlder` bigint(20) DEFAULT NULL,
  `Fodselsdato` date DEFAULT NULL,
  `Norsktalende` varchar(10) COLLATE utf8_danish_ci DEFAULT NULL,
  `Sivilstatus` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `Utdanning` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `Avdod` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdodDato` date DEFAULT NULL,
  `ForlopsID` varchar(10) COLLATE utf8_danish_ci NOT NULL,
  `BasisRegStatus` varchar(2) COLLATE utf8_danish_ci DEFAULT NULL,
  `ForlopsType1` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `ForlopsType1Num` varchar(2) COLLATE utf8_danish_ci DEFAULT NULL,
  `ForlopsType2` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ForlopsType2Num` varchar(2) COLLATE utf8_danish_ci DEFAULT NULL,
  `KobletForlopsID` varchar(10) COLLATE utf8_danish_ci DEFAULT NULL,
  `HovedDato` date DEFAULT NULL,
  `OppflgRegStatus` varchar(3) COLLATE utf8_danish_ci DEFAULT NULL,
  `ErOppflg` varchar(1) COLLATE utf8_danish_ci DEFAULT NULL,
  `OppflgStatus` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `OppflgSekNr` varchar(3) COLLATE utf8_danish_ci DEFAULT NULL,
  PRIMARY KEY (`ForlopsID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `fylke`;
CREATE TABLE `fylke` (
  `ID` char(2) COLLATE utf8_danish_ci NOT NULL,
  `NAVN` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `kjeder`;
CREATE TABLE `kjeder` (
  `ForlopsId` int(9) NOT NULL,
  `PasientId` int(10) unsigned DEFAULT NULL,
  `DatoForInnhenti` date DEFAULT NULL,
  `P_CREATEDBY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `P_UPDATEDBY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `P_GENDER` tinyint(3) DEFAULT NULL,
  `P_AGE` bigint(20) DEFAULT NULL,
  `P_ZIPCODE` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `P_TOWN` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `P_POSTSTED` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `P_KOMMUNE` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `P_KOMMUNENR` char(4) COLLATE utf8_danish_ci DEFAULT NULL,
  `P_FYLKESNR` char(2) COLLATE utf8_danish_ci DEFAULT NULL,
  `P_FYLKE` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `P_DECEASED` tinyint(3) DEFAULT NULL,
  `IS_STOPPED` int(11) DEFAULT NULL,
  `SykehusId` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `SykehusNavn` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `R_MCETYPE` tinyint(3) DEFAULT NULL,
  `R_HISTORICAL` tinyint(3) DEFAULT NULL,
  `R_STARTDATE` date DEFAULT NULL,
  `R_RHF` tinyint(3) DEFAULT NULL,
  `R_CENTRE` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `R_ART_O2` decimal(3,1) DEFAULT NULL,
  `R_ART_O2_MISS` tinyint(3) DEFAULT NULL,
  `R_ART_CO2` decimal(3,1) DEFAULT NULL,
  `R_ART_CO2_MISS` tinyint(3) DEFAULT NULL,
  `R_CO2_SLEEP` decimal(3,1) DEFAULT NULL,
  `R_CO2_SLEEP_MISS` tinyint(3) DEFAULT NULL,
  `R_HYPOVENT` tinyint(3) DEFAULT NULL,
  `R_HYPOVENT_PERC` decimal(4,1) DEFAULT NULL,
  `R_HYPOVENT_PERC_MISS` tinyint(3) DEFAULT NULL,
  `R_OXY_MEASUREMENT` tinyint(3) DEFAULT NULL,
  `R_SPO2_AVG_PERC` decimal(4,1) DEFAULT NULL,
  `R_SPO2_AVG_PERC_MISS` tinyint(3) DEFAULT NULL,
  `R_SPO2_UNDER90` decimal(4,1) DEFAULT NULL,
  `R_SPO2_UNDER90_MISS` tinyint(3) DEFAULT NULL,
  `R_CAP_O2` decimal(3,1) DEFAULT NULL,
  `R_CAP_O2_MISS` tinyint(3) DEFAULT NULL,
  `R_CAP_CO2` decimal(3,1) DEFAULT NULL,
  `R_CAP_CO2_MISS` tinyint(3) DEFAULT NULL,
  `R_BE` decimal(3,1) DEFAULT NULL,
  `R_BE_MISS` tinyint(3) DEFAULT NULL,
  `R_VC_SITTING` decimal(3,2) DEFAULT NULL,
  `R_VC_SITTING_MISS` tinyint(3) DEFAULT NULL,
  `R_VC_LYING` decimal(3,2) DEFAULT NULL,
  `R_VC_LYING_MISS` tinyint(3) DEFAULT NULL,
  `R_FVC` decimal(3,2) DEFAULT NULL,
  `R_FVC_MISS` tinyint(3) DEFAULT NULL,
  `R_FEV1` decimal(3,2) DEFAULT NULL,
  `R_FEV1_MISS` tinyint(3) DEFAULT NULL,
  `R_COUGHPEF` smallint(6) DEFAULT NULL,
  `R_COUGHPEF_MISS` tinyint(3) DEFAULT NULL,
  `R_HEIGHT` smallint(6) DEFAULT NULL,
  `R_HEIGHT_MISS` tinyint(3) DEFAULT NULL,
  `R_WEIGHT` decimal(4,1) DEFAULT NULL,
  `R_WEIGHT_MISS` tinyint(3) DEFAULT NULL,
  `R_BMI` decimal(16,5) DEFAULT NULL,
  `R_FVC_PP` decimal(4,1) DEFAULT NULL,
  `R_FEV1_PP` decimal(4,1) DEFAULT NULL,
  `R_DIAGNOSIS1` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `R_DIAGNOSISMAIN` varchar(150) COLLATE utf8_danish_ci DEFAULT NULL,
  `R_DIAGNOSIS1_OTHER` varchar(150) COLLATE utf8_danish_ci DEFAULT NULL,
  `R_DIAGNOSIS2` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `R_DIAGNOSISBI` varchar(150) COLLATE utf8_danish_ci DEFAULT NULL,
  `R_DIAGNOSIS2_OTHER` varchar(150) COLLATE utf8_danish_ci DEFAULT NULL,
  `R_SYMP_HEADACHE` tinyint(3) DEFAULT NULL,
  `R_SYMP_INSOMNIA` tinyint(3) DEFAULT NULL,
  `R_SYMP_INFECTION` tinyint(3) DEFAULT NULL,
  `R_SYMP_FATIGUE` tinyint(3) DEFAULT NULL,
  `R_SYMP_DYSPNEA` tinyint(3) DEFAULT NULL,
  `R_STARTUP` tinyint(3) DEFAULT NULL,
  `R_HOSPITALDAYS` smallint(6) DEFAULT NULL,
  `R_SITUATIONVENT` tinyint(3) DEFAULT NULL,
  `R_VENT_HOURS` tinyint(3) DEFAULT NULL,
  `R_VENT_MACHINE2` tinyint(3) DEFAULT NULL,
  `R_VENT_MACHINE` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `R_VENT_CONNECTION2` tinyint(3) DEFAULT NULL,
  `R_VENT_CONNECTION` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `R_TRACDATE` date DEFAULT NULL,
  `R_VENTASSIST` tinyint(3) DEFAULT NULL,
  `R_QUALITYOFLIFE` tinyint(3) DEFAULT NULL,
  `R_QL_WAKEUP` tinyint(3) DEFAULT NULL,
  `R_QL_HEADACHE` tinyint(3) DEFAULT NULL,
  `R_QL_RESTED` tinyint(3) DEFAULT NULL,
  `R_QL_SLEEPY` tinyint(3) DEFAULT NULL,
  `R_QL_DYSPNEA` tinyint(3) DEFAULT NULL,
  `R_QL_ESS` tinyint(3) DEFAULT NULL,
  `R_ADD_OXYGEN` tinyint(3) DEFAULT NULL,
  `R_ADD_HUMIDIFIER` tinyint(3) DEFAULT NULL,
  `R_ADD_RESPIRATOR` tinyint(3) DEFAULT NULL,
  `R_ADD_SUCTION` tinyint(3) DEFAULT NULL,
  `R_ADD_COUGH_MACHINE` tinyint(3) DEFAULT NULL,
  `R_ADD_OXIMETER` tinyint(3) DEFAULT NULL,
  `R_RESIDENTIALFORM` tinyint(3) DEFAULT NULL,
  `R_ZIPCODE` varchar(4) COLLATE utf8_danish_ci DEFAULT NULL,
  `R_TOWN` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `R_KOMMUNE` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `R_KOMMUNENR` varchar(4) COLLATE utf8_danish_ci DEFAULT NULL,
  `R_FYLKESNR` varchar(2) COLLATE utf8_danish_ci DEFAULT NULL,
  `R_FYLKE` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `R_WORKSTATUS` tinyint(3) DEFAULT NULL,
  `R_CARE_UNPAID_RELATIVES` tinyint(3) DEFAULT NULL,
  `R_CARE_PAID_RELATIVES` tinyint(3) DEFAULT NULL,
  `R_CARE_PERS_ASSISTANT` tinyint(3) DEFAULT NULL,
  `R_CARE_SERVICEHOUSING` tinyint(3) DEFAULT NULL,
  `R_CARE_TEAM` tinyint(3) DEFAULT NULL,
  `R_CARE_HOME_NURSING` tinyint(3) DEFAULT NULL,
  `R_CARE_NONE` tinyint(3) DEFAULT NULL,
  `R_CREATEDBY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `R_UPDATEDBY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `R_STATUS` tinyint(3) DEFAULT NULL,
  `F1_FID` int(10) unsigned DEFAULT NULL,
  `F1_CENTREID` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `F1_MCETYPE` tinyint(3) DEFAULT NULL,
  `F1_HISTORICAL` tinyint(3) DEFAULT NULL,
  `F1_PARENT_MCE` int(10) unsigned DEFAULT NULL,
  `F1_YEAR` tinyint(3) DEFAULT NULL,
  `F1_RHF` tinyint(3) DEFAULT NULL,
  `F1_CENTRE` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `F1_CENTRENAME` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `F1_ART_O2` decimal(3,1) DEFAULT NULL,
  `F1_ART_O2_MISS` tinyint(3) DEFAULT NULL,
  `F1_ART_CO2` decimal(3,1) DEFAULT NULL,
  `F1_ART_CO2_MISS` tinyint(3) DEFAULT NULL,
  `F1_CO2_SLEEP` decimal(3,1) DEFAULT NULL,
  `F1_CO2_SLEEP_MISS` tinyint(3) DEFAULT NULL,
  `F1_HYPOVENT` tinyint(3) DEFAULT NULL,
  `F1_HYPOVENT_PERC` decimal(4,1) DEFAULT NULL,
  `F1_HYPOVENT_PERC_MISS` tinyint(3) DEFAULT NULL,
  `F1_OXY_MEASUREMENT` tinyint(3) DEFAULT NULL,
  `F1_SPO2_AVG_PERC` decimal(4,1) DEFAULT NULL,
  `F1_SPO2_AVG_PERC_MISS` tinyint(3) DEFAULT NULL,
  `F1_SPO2_UNDER90` decimal(4,1) DEFAULT NULL,
  `F1_SPO2_UNDER90_MISS` tinyint(3) DEFAULT NULL,
  `F1_CAP_O2` decimal(3,1) DEFAULT NULL,
  `F1_CAP_O2_MISS` tinyint(3) DEFAULT NULL,
  `F1_CAP_CO2` decimal(3,1) DEFAULT NULL,
  `F1_CAP_CO2_MISS` tinyint(3) DEFAULT NULL,
  `F1_BE` decimal(3,1) DEFAULT NULL,
  `F1_BE_MISS` tinyint(3) DEFAULT NULL,
  `F1_VC_SITTING` decimal(2,1) DEFAULT NULL,
  `F1_VC_SITTING_MISS` tinyint(3) DEFAULT NULL,
  `F1_VC_LYING` decimal(2,1) DEFAULT NULL,
  `F1_VC_LYING_MISS` tinyint(3) DEFAULT NULL,
  `F1_FVC` decimal(2,1) DEFAULT NULL,
  `F1_FVC_MISS` tinyint(3) DEFAULT NULL,
  `F1_FEV1` decimal(2,1) DEFAULT NULL,
  `F1_FEV1_MISS` tinyint(3) DEFAULT NULL,
  `F1_COUGHPEF` smallint(6) DEFAULT NULL,
  `F1_COUGHPEF_MISS` tinyint(3) DEFAULT NULL,
  `F1_HEIGHT` smallint(6) DEFAULT NULL,
  `F1_HEIGHT_MISS` tinyint(3) DEFAULT NULL,
  `F1_WEIGHT` decimal(4,1) DEFAULT NULL,
  `F1_WEIGHT_MISS` tinyint(3) DEFAULT NULL,
  `F1_FVC_PP` decimal(4,1) DEFAULT NULL,
  `F1_FEV1_PP` decimal(4,1) DEFAULT NULL,
  `F1_VENT_HOURS` tinyint(3) DEFAULT NULL,
  `F1_VENT_MACHINE2` tinyint(3) DEFAULT NULL,
  `F1_VENT_MACHINE` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `F1_VENT_CONNECTION2` tinyint(3) DEFAULT NULL,
  `F1_VENT_CONNECTION` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `F1_TRACDATE` date DEFAULT NULL,
  `F1_VENTASSIST` tinyint(3) DEFAULT NULL,
  `F1_FOLLOWUP_DATE` date DEFAULT NULL,
  `F1_STOP` tinyint(3) DEFAULT NULL,
  `F1_QUALITYOFLIFE` tinyint(3) DEFAULT NULL,
  `F1_QL_WAKEUP` tinyint(3) DEFAULT NULL,
  `F1_QL_HEADACHE` tinyint(3) DEFAULT NULL,
  `F1_QL_RESTED` tinyint(3) DEFAULT NULL,
  `F1_QL_SLEEPY` tinyint(3) DEFAULT NULL,
  `F1_QL_DYSPNEA` tinyint(3) DEFAULT NULL,
  `F1_QL_ESS` tinyint(3) DEFAULT NULL,
  `F1_ADD_OXYGEN` tinyint(3) DEFAULT NULL,
  `F1_ADD_HUMIDIFIER` tinyint(3) DEFAULT NULL,
  `F1_ADD_SPARE_RESP` tinyint(3) DEFAULT NULL,
  `F1_ADD_SUCTION` tinyint(3) DEFAULT NULL,
  `F1_ADD_COUGHMACHINE` tinyint(3) DEFAULT NULL,
  `F1_ADD_OXIMETER` tinyint(3) DEFAULT NULL,
  `F1_RESIDENTIALFORM` tinyint(3) DEFAULT NULL,
  `F1_ZIPCODE` varchar(4) COLLATE utf8_danish_ci DEFAULT NULL,
  `F1_TOWN` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `F1_KOMMUNE` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `F1_KOMMUNENR` varchar(4) COLLATE utf8_danish_ci DEFAULT NULL,
  `F1_FYLKESNR` varchar(2) COLLATE utf8_danish_ci DEFAULT NULL,
  `F1_FYLKE` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `F1_WORKSTATUS` tinyint(3) DEFAULT NULL,
  `F1_CARE_UNPAID_RELATIVES` tinyint(3) DEFAULT NULL,
  `F1_CARE_PAID_RELATIVES` tinyint(3) DEFAULT NULL,
  `F1_CARE_PERS_ASSISTANT` tinyint(3) DEFAULT NULL,
  `F1_CARE_SERVICEHOUSING` tinyint(3) DEFAULT NULL,
  `F1_CARE_TEAM` tinyint(3) DEFAULT NULL,
  `F1_CARE_HOME_NURSING` tinyint(3) DEFAULT NULL,
  `F1_CARE_NONE` tinyint(3) DEFAULT NULL,
  `F1_CREATEDBY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `F1_UPDATEDBY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `F1_STATUS` tinyint(3) DEFAULT NULL,
  `F3_FID` int(10) unsigned DEFAULT NULL,
  `F3_CENTREID` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `F3_MCETYPE` tinyint(3) DEFAULT NULL,
  `F3_HISTORICAL` tinyint(3) DEFAULT NULL,
  `F3_PARENT_MCE` int(10) unsigned DEFAULT NULL,
  `F3_YEAR` tinyint(3) DEFAULT NULL,
  `F3_RHF` tinyint(3) DEFAULT NULL,
  `F3_CENTRE` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `F3_CENTRENAME` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `F3_ART_O2` decimal(3,1) DEFAULT NULL,
  `F3_ART_O2_MISS` tinyint(3) DEFAULT NULL,
  `F3_ART_CO2` decimal(3,1) DEFAULT NULL,
  `F3_ART_CO2_MISS` tinyint(3) DEFAULT NULL,
  `F3_CO2_SLEEP` decimal(3,1) DEFAULT NULL,
  `F3_CO2_SLEEP_MISS` tinyint(3) DEFAULT NULL,
  `F3_HYPOVENT` tinyint(3) DEFAULT NULL,
  `F3_HYPOVENT_PERC` decimal(4,1) DEFAULT NULL,
  `F3_HYPOVENT_PERC_MISS` tinyint(3) DEFAULT NULL,
  `F3_OXY_MEASUREMENT` tinyint(3) DEFAULT NULL,
  `F3_SPO2_AVG_PERC` decimal(4,1) DEFAULT NULL,
  `F3_SPO2_AVG_PERC_MISS` tinyint(3) DEFAULT NULL,
  `F3_SPO2_UNDER90` decimal(4,1) DEFAULT NULL,
  `F3_SPO2_UNDER90_MISS` tinyint(3) DEFAULT NULL,
  `F3_CAP_O2` decimal(3,1) DEFAULT NULL,
  `F3_CAP_O2_MISS` tinyint(3) DEFAULT NULL,
  `F3_CAP_CO2` decimal(3,1) DEFAULT NULL,
  `F3_CAP_CO2_MISS` tinyint(3) DEFAULT NULL,
  `F3_BE` decimal(3,1) DEFAULT NULL,
  `F3_BE_MISS` tinyint(3) DEFAULT NULL,
  `F3_VC_SITTING` decimal(2,1) DEFAULT NULL,
  `F3_VC_SITTING_MISS` tinyint(3) DEFAULT NULL,
  `F3_VC_LYING` decimal(2,1) DEFAULT NULL,
  `F3_VC_LYING_MISS` tinyint(3) DEFAULT NULL,
  `F3_FVC` decimal(2,1) DEFAULT NULL,
  `F3_FVC_MISS` tinyint(3) DEFAULT NULL,
  `F3_FEV1` decimal(2,1) DEFAULT NULL,
  `F3_FEV1_MISS` tinyint(3) DEFAULT NULL,
  `F3_COUGHPEF` smallint(6) DEFAULT NULL,
  `F3_COUGHPEF_MISS` tinyint(3) DEFAULT NULL,
  `F3_HEIGHT` smallint(6) DEFAULT NULL,
  `F3_HEIGHT_MISS` tinyint(3) DEFAULT NULL,
  `F3_WEIGHT` decimal(4,1) DEFAULT NULL,
  `F3_WEIGHT_MISS` tinyint(3) DEFAULT NULL,
  `F3_FVC_PP` decimal(4,1) DEFAULT NULL,
  `F3_FEV1_PP` decimal(4,1) DEFAULT NULL,
  `F3_VENT_HOURS` tinyint(3) DEFAULT NULL,
  `F3_VENT_MACHINE2` tinyint(3) DEFAULT NULL,
  `F3_VENT_MACHINE` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `F3_VENT_CONNECTION2` tinyint(3) DEFAULT NULL,
  `F3_VENT_CONNECTION` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `F3_TRACDATE` date DEFAULT NULL,
  `F3_VENTASSIST` tinyint(3) DEFAULT NULL,
  `F3_FOLLOWUP_DATE` date DEFAULT NULL,
  `F3_STOP` tinyint(3) DEFAULT NULL,
  `F3_QUALITYOFLIFE` tinyint(3) DEFAULT NULL,
  `F3_QL_WAKEUP` tinyint(3) DEFAULT NULL,
  `F3_QL_HEADACHE` tinyint(3) DEFAULT NULL,
  `F3_QL_RESTED` tinyint(3) DEFAULT NULL,
  `F3_QL_SLEEPY` tinyint(3) DEFAULT NULL,
  `F3_QL_DYSPNEA` tinyint(3) DEFAULT NULL,
  `F3_QL_ESS` tinyint(3) DEFAULT NULL,
  `F3_ADD_OXYGEN` tinyint(3) DEFAULT NULL,
  `F3_ADD_HUMIDIFIER` tinyint(3) DEFAULT NULL,
  `F3_ADD_SPARE_RESP` tinyint(3) DEFAULT NULL,
  `F3_ADD_SUCTION` tinyint(3) DEFAULT NULL,
  `F3_ADD_COUGHMACHINE` tinyint(3) DEFAULT NULL,
  `F3_ADD_OXIMETER` tinyint(3) DEFAULT NULL,
  `F3_RESIDENTIALFORM` tinyint(3) DEFAULT NULL,
  `F3_ZIPCODE` varchar(4) COLLATE utf8_danish_ci DEFAULT NULL,
  `F3_TOWN` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `F3_KOMMUNE` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `F3_KOMMUNENR` varchar(4) COLLATE utf8_danish_ci DEFAULT NULL,
  `F3_FYLKESNR` varchar(2) COLLATE utf8_danish_ci DEFAULT NULL,
  `F3_FYLKE` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `F3_WORKSTATUS` tinyint(3) DEFAULT NULL,
  `F3_CARE_UNPAID_RELATIVES` tinyint(3) DEFAULT NULL,
  `F3_CARE_PAID_RELATIVES` tinyint(3) DEFAULT NULL,
  `F3_CARE_PERS_ASSISTANT` tinyint(3) DEFAULT NULL,
  `F3_CARE_SERVICEHOUSING` tinyint(3) DEFAULT NULL,
  `F3_CARE_TEAM` tinyint(3) DEFAULT NULL,
  `F3_CARE_HOME_NURSING` tinyint(3) DEFAULT NULL,
  `F3_CARE_NONE` tinyint(3) DEFAULT NULL,
  `F3_CREATEDBY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `F3_UPDATEDBY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `F3_STATUS` tinyint(3) DEFAULT NULL,
  `LF_FID` int(10) unsigned DEFAULT NULL,
  `LF_CENTREID` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `LF_MCETYPE` tinyint(3) DEFAULT NULL,
  `LF_HISTORICAL` tinyint(3) DEFAULT NULL,
  `LF_PARENT_MCE` int(10) unsigned DEFAULT NULL,
  `LF_YEAR` tinyint(3) DEFAULT NULL,
  `LF_RHF` tinyint(3) DEFAULT NULL,
  `LF_CENTRE` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `LF_CENTRENAME` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LF_ART_O2` decimal(3,1) DEFAULT NULL,
  `LF_ART_O2_MISS` tinyint(3) DEFAULT NULL,
  `LF_ART_CO2` decimal(3,1) DEFAULT NULL,
  `LF_ART_CO2_MISS` tinyint(3) DEFAULT NULL,
  `LF_CO2_SLEEP` decimal(3,1) DEFAULT NULL,
  `LF_CO2_SLEEP_MISS` tinyint(3) DEFAULT NULL,
  `LF_HYPOVENT` tinyint(3) DEFAULT NULL,
  `LF_HYPOVENT_PERC` decimal(4,1) DEFAULT NULL,
  `LF_HYPOVENT_PERC_MISS` tinyint(3) DEFAULT NULL,
  `LF_OXY_MEASUREMENT` tinyint(3) DEFAULT NULL,
  `LF_SPO2_AVG_PERC` decimal(4,1) DEFAULT NULL,
  `LF_SPO2_AVG_PERC_MISS` tinyint(3) DEFAULT NULL,
  `LF_SPO2_UNDER90` decimal(4,1) DEFAULT NULL,
  `LF_SPO2_UNDER90_MISS` tinyint(3) DEFAULT NULL,
  `LF_CAP_O2` decimal(3,1) DEFAULT NULL,
  `LF_CAP_O2_MISS` tinyint(3) DEFAULT NULL,
  `LF_CAP_CO2` decimal(3,1) DEFAULT NULL,
  `LF_CAP_CO2_MISS` tinyint(3) DEFAULT NULL,
  `LF_BE` decimal(3,1) DEFAULT NULL,
  `LF_BE_MISS` tinyint(3) DEFAULT NULL,
  `LF_VC_SITTING` decimal(2,1) DEFAULT NULL,
  `LF_VC_SITTING_MISS` tinyint(3) DEFAULT NULL,
  `LF_VC_LYING` decimal(2,1) DEFAULT NULL,
  `LF_VC_LYING_MISS` tinyint(3) DEFAULT NULL,
  `LF_FVC` decimal(2,1) DEFAULT NULL,
  `LF_FVC_MISS` tinyint(3) DEFAULT NULL,
  `LF_FEV1` decimal(2,1) DEFAULT NULL,
  `LF_FEV1_MISS` tinyint(3) DEFAULT NULL,
  `LF_COUGHPEF` smallint(6) DEFAULT NULL,
  `LF_COUGHPEF_MISS` tinyint(3) DEFAULT NULL,
  `LF_HEIGHT` smallint(6) DEFAULT NULL,
  `LF_HEIGHT_MISS` tinyint(3) DEFAULT NULL,
  `LF_WEIGHT` decimal(4,1) DEFAULT NULL,
  `LF_WEIGHT_MISS` tinyint(3) DEFAULT NULL,
  `LF_FVC_PP` decimal(4,1) DEFAULT NULL,
  `LF_FEV1_PP` decimal(4,1) DEFAULT NULL,
  `LF_VENT_HOURS` tinyint(3) DEFAULT NULL,
  `LF_VENT_MACHINE2` tinyint(3) DEFAULT NULL,
  `LF_VENT_MACHINE` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LF_VENT_CONNECTION2` tinyint(3) DEFAULT NULL,
  `LF_VENT_CONNECTION` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LF_TRACDATE` date DEFAULT NULL,
  `LF_VENTASSIST` tinyint(3) DEFAULT NULL,
  `LF_FOLLOWUP_DATE` date DEFAULT NULL,
  `LF_STOP` tinyint(3) DEFAULT NULL,
  `LF_QUALITYOFLIFE` tinyint(3) DEFAULT NULL,
  `LF_QL_WAKEUP` tinyint(3) DEFAULT NULL,
  `LF_QL_HEADACHE` tinyint(3) DEFAULT NULL,
  `LF_QL_RESTED` tinyint(3) DEFAULT NULL,
  `LF_QL_SLEEPY` tinyint(3) DEFAULT NULL,
  `LF_QL_DYSPNEA` tinyint(3) DEFAULT NULL,
  `LF_QL_ESS` tinyint(3) DEFAULT NULL,
  `LF_ADD_OXYGEN` tinyint(3) DEFAULT NULL,
  `LF_ADD_HUMIDIFIER` tinyint(3) DEFAULT NULL,
  `LF_ADD_SPARE_RESP` tinyint(3) DEFAULT NULL,
  `LF_ADD_SUCTION` tinyint(3) DEFAULT NULL,
  `LF_ADD_COUGHMACHINE` tinyint(3) DEFAULT NULL,
  `LF_ADD_OXIMETER` tinyint(3) DEFAULT NULL,
  `LF_RESIDENTIALFORM` tinyint(3) DEFAULT NULL,
  `LF_ZIPCODE` varchar(4) COLLATE utf8_danish_ci DEFAULT NULL,
  `LF_TOWN` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `LF_KOMMUNE` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `LF_KOMMUNENR` varchar(4) COLLATE utf8_danish_ci DEFAULT NULL,
  `LF_FYLKESNR` varchar(2) COLLATE utf8_danish_ci DEFAULT NULL,
  `LF_FYLKE` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `LF_WORKSTATUS` tinyint(3) DEFAULT NULL,
  `LF_CARE_UNPAID_RELATIVES` tinyint(3) DEFAULT NULL,
  `LF_CARE_PAID_RELATIVES` tinyint(3) DEFAULT NULL,
  `LF_CARE_PERS_ASSISTANT` tinyint(3) DEFAULT NULL,
  `LF_CARE_SERVICEHOUSING` tinyint(3) DEFAULT NULL,
  `LF_CARE_TEAM` tinyint(3) DEFAULT NULL,
  `LF_CARE_HOME_NURSING` tinyint(3) DEFAULT NULL,
  `LF_CARE_NONE` tinyint(3) DEFAULT NULL,
  `LF_CREATEDBY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `LF_UPDATEDBY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `LF_STATUS` tinyint(3) DEFAULT NULL,
  `FAH_FID` int(10) unsigned DEFAULT NULL,
  `FAH_CENTREID` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `FAH_MCETYPE` tinyint(3) DEFAULT NULL,
  `FAH_HISTORICAL` tinyint(3) DEFAULT NULL,
  `FAH_PARENT_MCE` int(10) unsigned DEFAULT NULL,
  `FAH_YEAR` tinyint(3) DEFAULT NULL,
  `FAH_RHF` tinyint(3) DEFAULT NULL,
  `FAH_CENTRE` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `FAH_CENTRENAME` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `FAH_ART_O2` decimal(3,1) DEFAULT NULL,
  `FAH_ART_O2_MISS` tinyint(3) DEFAULT NULL,
  `FAH_ART_CO2` decimal(3,1) DEFAULT NULL,
  `FAH_ART_CO2_MISS` tinyint(3) DEFAULT NULL,
  `FAH_CO2_SLEEP` decimal(3,1) DEFAULT NULL,
  `FAH_CO2_SLEEP_MISS` tinyint(3) DEFAULT NULL,
  `FAH_HYPOVENT` tinyint(3) DEFAULT NULL,
  `FAH_HYPOVENT_PERC` decimal(4,1) DEFAULT NULL,
  `FAH_HYPOVENT_PERC_MISS` tinyint(3) DEFAULT NULL,
  `FAH_OXY_MEASUREMENT` tinyint(3) DEFAULT NULL,
  `FAH_SPO2_AVG_PERC` decimal(4,1) DEFAULT NULL,
  `FAH_SPO2_AVG_PERC_MISS` tinyint(3) DEFAULT NULL,
  `FAH_SPO2_UNDER90` decimal(4,1) DEFAULT NULL,
  `FAH_SPO2_UNDER90_MISS` tinyint(3) DEFAULT NULL,
  `FAH_CAP_O2` decimal(3,1) DEFAULT NULL,
  `FAH_CAP_O2_MISS` tinyint(3) DEFAULT NULL,
  `FAH_CAP_CO2` decimal(3,1) DEFAULT NULL,
  `FAH_CAP_CO2_MISS` tinyint(3) DEFAULT NULL,
  `FAH_BE` decimal(3,1) DEFAULT NULL,
  `FAH_BE_MISS` tinyint(3) DEFAULT NULL,
  `FAH_VC_SITTING` decimal(2,1) DEFAULT NULL,
  `FAH_VC_SITTING_MISS` tinyint(3) DEFAULT NULL,
  `FAH_VC_LYING` decimal(2,1) DEFAULT NULL,
  `FAH_VC_LYING_MISS` tinyint(3) DEFAULT NULL,
  `FAH_FVC` decimal(2,1) DEFAULT NULL,
  `FAH_FVC_MISS` tinyint(3) DEFAULT NULL,
  `FAH_FEV1` decimal(2,1) DEFAULT NULL,
  `FAH_FEV1_MISS` tinyint(3) DEFAULT NULL,
  `FAH_COUGHPEF` smallint(6) DEFAULT NULL,
  `FAH_COUGHPEF_MISS` tinyint(3) DEFAULT NULL,
  `FAH_HEIGHT` smallint(6) DEFAULT NULL,
  `FAH_HEIGHT_MISS` tinyint(3) DEFAULT NULL,
  `FAH_WEIGHT` decimal(4,1) DEFAULT NULL,
  `FAH_WEIGHT_MISS` tinyint(3) DEFAULT NULL,
  `FAH_FVC_PP` decimal(4,1) DEFAULT NULL,
  `FAH_FEV1_PP` decimal(4,1) DEFAULT NULL,
  `FAH_VENT_HOURS` tinyint(3) DEFAULT NULL,
  `FAH_VENT_MACHINE2` tinyint(3) DEFAULT NULL,
  `FAH_VENT_MACHINE` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `FAH_VENT_CONNECTION2` tinyint(3) DEFAULT NULL,
  `FAH_VENT_CONNECTION` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `FAH_TRACDATE` date DEFAULT NULL,
  `FAH_VENTASSIST` tinyint(3) DEFAULT NULL,
  `FAH_FOLLOWUP_DATE` date DEFAULT NULL,
  `FAH_STOP` tinyint(3) DEFAULT NULL,
  `FAH_QUALITYOFLIFE` tinyint(3) DEFAULT NULL,
  `FAH_QL_WAKEUP` tinyint(3) DEFAULT NULL,
  `FAH_QL_HEADACHE` tinyint(3) DEFAULT NULL,
  `FAH_QL_RESTED` tinyint(3) DEFAULT NULL,
  `FAH_QL_SLEEPY` tinyint(3) DEFAULT NULL,
  `FAH_QL_DYSPNEA` tinyint(3) DEFAULT NULL,
  `FAH_QL_ESS` tinyint(3) DEFAULT NULL,
  `FAH_ADD_OXYGEN` tinyint(3) DEFAULT NULL,
  `FAH_ADD_HUMIDIFIER` tinyint(3) DEFAULT NULL,
  `FAH_ADD_SPARE_RESP` tinyint(3) DEFAULT NULL,
  `FAH_ADD_SUCTION` tinyint(3) DEFAULT NULL,
  `FAH_ADD_COUGHMACHINE` tinyint(3) DEFAULT NULL,
  `FAH_ADD_OXIMETER` tinyint(3) DEFAULT NULL,
  `FAH_RESIDENTIALFORM` tinyint(3) DEFAULT NULL,
  `FAH_ZIPCODE` varchar(4) COLLATE utf8_danish_ci DEFAULT NULL,
  `FAH_TOWN` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `FAH_KOMMUNE` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `FAH_KOMMUNENR` varchar(4) COLLATE utf8_danish_ci DEFAULT NULL,
  `FAH_FYLKESNR` varchar(2) COLLATE utf8_danish_ci DEFAULT NULL,
  `FAH_FYLKE` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `FAH_WORKSTATUS` tinyint(3) DEFAULT NULL,
  `FAH_CARE_UNPAID_RELATIVES` tinyint(3) DEFAULT NULL,
  `FAH_CARE_PAID_RELATIVES` tinyint(3) DEFAULT NULL,
  `FAH_CARE_PERS_ASSISTANT` tinyint(3) DEFAULT NULL,
  `FAH_CARE_SERVICEHOUSING` tinyint(3) DEFAULT NULL,
  `FAH_CARE_TEAM` tinyint(3) DEFAULT NULL,
  `FAH_CARE_HOME_NURSING` tinyint(3) DEFAULT NULL,
  `FAH_CARE_NONE` tinyint(3) DEFAULT NULL,
  `FAH_CREATEDBY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `FAH_UPDATEDBY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `FAH_STATUS` tinyint(3) DEFAULT NULL,
  `C_FID` int(10) unsigned DEFAULT NULL,
  `C_CENTREID` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `C_RHF` tinyint(3) DEFAULT NULL,
  `C_CENTRE` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `C_CENTRENAME` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `C_STOPDATE` date DEFAULT NULL,
  `C_STOPDATE_MISS` tinyint(3) DEFAULT NULL,
  `C_STOP_CAUSE` tinyint(3) DEFAULT NULL,
  `C_STILL_ALIVE` tinyint(3) DEFAULT NULL,
  `C_DEATH_CAUSE` tinyint(3) DEFAULT NULL,
  `C_DECEASED_DATE` date DEFAULT NULL,
  `C_DECEASED_DATE_MISS` tinyint(3) DEFAULT NULL,
  `C_CREATEDBY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `C_UPDATEDBY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `C_STATUS` tinyint(3) DEFAULT NULL,
  `CHAIN_IS_STOPPED` int(11) DEFAULT NULL,
  `CHAIN_IS_CONCLUDED` int(11) DEFAULT NULL,
  `CHAIN_BASEREG_STATUS` varchar(2) COLLATE utf8_danish_ci DEFAULT NULL,
  PRIMARY KEY (`ForlopsId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `kommune`;
CREATE TABLE `kommune` (
  `ID` char(4) COLLATE utf8_danish_ci DEFAULT NULL,
  `NAVN` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `FYLKE_ID` char(2) COLLATE utf8_danish_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `mce`;
CREATE TABLE `mce` (
  `MCEID` int(9) NOT NULL,
  `CENTREID` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `PATIENT_ID` int(10) unsigned DEFAULT NULL,
  `MCETYPE` tinyint(3) DEFAULT NULL,
  `PARENT_MCE` int(10) unsigned DEFAULT NULL,
  `END_DATE` date DEFAULT NULL,
  `MCE_TOTAL_STATUS` tinyint(3) DEFAULT NULL,
  `REGISTRATION_DATE` date DEFAULT NULL,
  `LAST_FOLLOWUP_YEAR` tinyint(3) DEFAULT NULL,
  `STATUS` tinyint(3) DEFAULT NULL,
  `HISTORICAL` tinyint(3) DEFAULT NULL,
  `CREATEDBY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `UPDATEDBY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `FIRST_TIME_CLOSED` timestamp NULL DEFAULT NULL,
  `FIRST_TIME_CLOSED_BY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `TSCREATED` timestamp NULL DEFAULT NULL,
  `TSUPDATED` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`MCEID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `patient`;
CREATE TABLE `patient` (
  `ID` int(10) unsigned DEFAULT NULL,
  `LAST_FREG_DATE` date DEFAULT NULL,
  `REGISTERED_DATE` date DEFAULT NULL,
  `SSN` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `SSN_TYPE` tinyint(3) DEFAULT NULL,
  `SSNSUBTYPE` tinyint(3) DEFAULT NULL,
  `GENDER` tinyint(3) DEFAULT NULL,
  `FIRSTNAME` varchar(60) COLLATE utf8_danish_ci DEFAULT NULL,
  `LASTNAME` varchar(60) COLLATE utf8_danish_ci DEFAULT NULL,
  `BIRTH_DATE` date DEFAULT NULL,
  `ADDRESS` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DISTRICTCODE` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DISTRICTNAME` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `ZIPCODE` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `TOWN` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `COUNTY` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `MUNICIPALITY_NAME` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `MUNICIPALITY_NUMBER` varchar(4) COLLATE utf8_danish_ci DEFAULT NULL,
  `FREEFORM_ADDR` varchar(500) COLLATE utf8_danish_ci DEFAULT NULL,
  `PHONE` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ALT_PHONE` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `EMAIL` varchar(150) COLLATE utf8_danish_ci DEFAULT NULL,
  `DECEASED` tinyint(3) DEFAULT NULL,
  `DECEASED_DATE` date DEFAULT NULL,
  `REAPER_DATE` date DEFAULT NULL,
  `ADDR_TYPE` tinyint(3) DEFAULT NULL,
  `USERCOMMENT` varchar(2000) COLLATE utf8_danish_ci DEFAULT NULL,
  `OWNING_CENTRE` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `CREATEDBY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `UPDATEDBY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `TSCREATED` timestamp NULL DEFAULT NULL,
  `TSUPDATED` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `postnr`;
CREATE TABLE `postnr` (
  `ID` char(4) COLLATE utf8_danish_ci NOT NULL,
  `POSTSTED` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `KOMMUNE_ID` char(4) COLLATE utf8_danish_ci DEFAULT NULL,
  `KATEGORI_ID` char(1) COLLATE utf8_danish_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `SkjemaOversikt`;
CREATE TABLE `SkjemaOversikt` (
  `Skjemanavn` varchar(18) COLLATE utf8_danish_ci NOT NULL,
  `SkjemaStatus` varchar(3) COLLATE utf8_danish_ci DEFAULT NULL,
  `ForlopsID` varchar(10) COLLATE utf8_danish_ci NOT NULL,
  `OpprettetAv` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `OpprettetDato` timestamp NULL DEFAULT NULL,
  `SistLagretAv` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `SistLagretDato` timestamp NULL DEFAULT NULL,
  `HovedDato` date DEFAULT NULL,
  `Sykehusnavn` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdRESH` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `SkjemaRekkeflg` decimal(6,3) DEFAULT NULL,
  PRIMARY KEY (`ForlopsID`,`Skjemanavn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `ventfol`;
CREATE TABLE `ventfol` (
  `CENTREID` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `MCEID` int(9) NOT NULL,
  `YEAR` tinyint(3) NOT NULL,
  `MOVE_TO_RHF` tinyint(3) DEFAULT NULL,
  `MOVE_TO_CENTRE` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `MOVE_TO_HOSPITAL` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `HOSPITAL_DEPARTMENT` tinyint(3) DEFAULT NULL,
  `PO2_AIR` decimal(3,1) DEFAULT NULL,
  `PO2_AIR_MISS` tinyint(3) DEFAULT NULL,
  `PCO2_AIR` decimal(3,1) DEFAULT NULL,
  `PCO2_AIR_MISS` tinyint(3) DEFAULT NULL,
  `ARTERIALPCO2_AIR` decimal(3,1) DEFAULT NULL,
  `ARTERIALPCO2_AIR_MISS` tinyint(3) DEFAULT NULL,
  `HYPOVENTILATION` tinyint(3) DEFAULT NULL,
  `HYPOVENTILATION_PERCENT` decimal(4,1) DEFAULT NULL,
  `HYPOVENTILATION_PERCENT_MISS` tinyint(3) DEFAULT NULL,
  `OXY_MEASUREMENT` tinyint(3) DEFAULT NULL,
  `SPO2_AVG_PERCENT` decimal(4,1) DEFAULT NULL,
  `SPO2_AVG_PERCENT_MISS` tinyint(3) DEFAULT NULL,
  `HYPO_PERCENT_OF_NIGHT` decimal(4,1) DEFAULT NULL,
  `HYPO_PERCENT_OF_NIGHT_MISS` tinyint(3) DEFAULT NULL,
  `CAPILLARYPO2_AIR` decimal(3,1) DEFAULT NULL,
  `CAPILLARYPO2_AIR_MISS` tinyint(3) DEFAULT NULL,
  `CAPILLARYPCO2_AIR` decimal(3,1) DEFAULT NULL,
  `CAPILLARYPCO2_AIR_MISS` tinyint(3) DEFAULT NULL,
  `BE` decimal(3,1) DEFAULT NULL,
  `BE_CAPILLARY` decimal(3,1) DEFAULT NULL,
  `BE_CAPILLARY_MISS` tinyint(3) DEFAULT NULL,
  `IS_CAPILLARY` tinyint(3) DEFAULT NULL,
  `BE_MISS` tinyint(3) DEFAULT NULL,
  `VC` decimal(2,1) DEFAULT NULL,
  `VC_MISS` tinyint(3) DEFAULT NULL,
  `VC_LYING` decimal(2,1) DEFAULT NULL,
  `VC_LYING_MISS` tinyint(3) DEFAULT NULL,
  `VC_SUPINE` decimal(2,1) DEFAULT NULL,
  `VC_SUPINE_MISS` tinyint(3) DEFAULT NULL,
  `FEV1` decimal(2,1) DEFAULT NULL,
  `FEV1_MISS` tinyint(3) DEFAULT NULL,
  `HOSTEPEF` smallint(6) DEFAULT NULL,
  `HOSTEPEF_MISS` tinyint(3) DEFAULT NULL,
  `HEIGHT` smallint(6) DEFAULT NULL,
  `HEIGHT_MISS` tinyint(3) DEFAULT NULL,
  `WEIGHT` decimal(4,1) DEFAULT NULL,
  `WEIGHT_MISS` tinyint(3) DEFAULT NULL,
  `VC_PERCENT_PREDICTED` decimal(4,1) DEFAULT NULL,
  `FEV1_PERCENT_PREDICTED` decimal(4,1) DEFAULT NULL,
  `VENTILATION_HOURS` tinyint(3) DEFAULT NULL,
  `VENTILATION_METHOD` tinyint(3) DEFAULT NULL,
  `VENTILATION_FRENIKUS` tinyint(3) DEFAULT NULL,
  `RESPCON` tinyint(3) DEFAULT NULL,
  `TRAKEOSTOMI_DATE` date DEFAULT NULL,
  `VENTILATION_ASSISTANCE` tinyint(3) DEFAULT NULL,
  `FOLLOWUP_DATE` date DEFAULT NULL,
  `STOP` tinyint(3) DEFAULT NULL,
  `FORM_COMPLETED_VIA_PROMS` tinyint(3) DEFAULT NULL,
  `EPROM_DATE` date DEFAULT NULL,
  `QUALITYOFLIFE` tinyint(3) DEFAULT NULL,
  `QLWAKEUP` tinyint(3) DEFAULT NULL,
  `QLHEADACHE` tinyint(3) DEFAULT NULL,
  `QLRESTED` tinyint(3) DEFAULT NULL,
  `QLSLEEPY` tinyint(3) DEFAULT NULL,
  `QLDYSPNOEA` tinyint(3) DEFAULT NULL,
  `QLESS` tinyint(3) DEFAULT NULL,
  `ADDITIONAL_OXYGEN` tinyint(3) DEFAULT NULL,
  `ADDITIONAL_HUMIDIFIER` tinyint(3) DEFAULT NULL,
  `ADDITIONAL_SPARE_RESP` tinyint(3) DEFAULT NULL,
  `ADDITIONAL_SUCTION` tinyint(3) DEFAULT NULL,
  `ADDITIONAL_COUGH_MACHINE` tinyint(3) DEFAULT NULL,
  `ADDITIONAL_OXIMETER` tinyint(3) DEFAULT NULL,
  `ADDITIONAL_TUBE_FEEDING` tinyint(3) DEFAULT NULL,
  `RESIDENTIAL_FORM` tinyint(3) DEFAULT NULL,
  `ZIPCODE` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `TOWN` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `MUNICIPALITY_NUMBER` varchar(4) COLLATE utf8_danish_ci DEFAULT NULL,
  `MUNICIPALITY_NAME` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `COUNTY` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `WORK_STATUS` tinyint(3) DEFAULT NULL,
  `CARE_SERVICES_UNPAID_RELATIVES` tinyint(3) DEFAULT NULL,
  `CARE_SERVICES_PAID_RELATIVES` tinyint(3) DEFAULT NULL,
  `CARE_SERVICES_USER_PERS_ASSISTANT` tinyint(3) DEFAULT NULL,
  `CARE_SERVICES_SERVICE_HOUSING` tinyint(3) DEFAULT NULL,
  `CARE_SERVICES_TEAM` tinyint(3) DEFAULT NULL,
  `CARE_SERVICES_HOME_NURSING` tinyint(3) DEFAULT NULL,
  `CARE_SERVICES_UNKNOWN` tinyint(3) DEFAULT NULL,
  `USERCOMMENT` varchar(2000) COLLATE utf8_danish_ci DEFAULT NULL,
  `STATUS` tinyint(3) DEFAULT NULL,
  `TSUPDATED` timestamp NULL DEFAULT NULL,
  `UPDATEDBY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `FIRST_TIME_CLOSED` timestamp NULL DEFAULT NULL,
  `FIRST_TIME_CLOSED_BY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `TSCREATED` timestamp NULL DEFAULT NULL,
  `CREATEDBY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `ventreg`;
CREATE TABLE `ventreg` (
  `MCEID` int(9) NOT NULL,
  `CENTREID` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `START_DATE` date DEFAULT NULL,
  `MOVE_TO_RHF` tinyint(3) DEFAULT NULL,
  `MOVE_TO_CENTRE` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `MOVE_TO_HOSPITAL` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `HOSPITAL_DEPARTMENT` tinyint(3) DEFAULT NULL,
  `PO2_AIR` decimal(3,1) DEFAULT NULL,
  `PO2_AIR_MISS` tinyint(3) DEFAULT NULL,
  `PCO2_AIR` decimal(3,1) DEFAULT NULL,
  `PCO2_AIR_MISS` tinyint(3) DEFAULT NULL,
  `ARTERIALPCO2_AIR` decimal(3,1) DEFAULT NULL,
  `ARTERIALPCO2_AIR_MISS` tinyint(3) DEFAULT NULL,
  `HYPOVENTILATION` tinyint(3) DEFAULT NULL,
  `HYPOVENTILATION_PERCENT` decimal(4,1) DEFAULT NULL,
  `HYPOVENTILATION_PERCENT_MISS` tinyint(3) DEFAULT NULL,
  `OXY_MEASUREMENT` tinyint(3) DEFAULT NULL,
  `SPO2_AVG_PERCENT` decimal(4,1) DEFAULT NULL,
  `SPO2_AVG_PERCENT_MISS` tinyint(3) DEFAULT NULL,
  `HYPO_PERCENT_OF_NIGHT` decimal(4,1) DEFAULT NULL,
  `HYPO_PERCENT_OF_NIGHT_MISS` tinyint(3) DEFAULT NULL,
  `CAPILLARYPO2_AIR` decimal(3,1) DEFAULT NULL,
  `CAPILLARYPO2_AIR_MISS` tinyint(3) DEFAULT NULL,
  `CAPILLARYPCO2_AIR` decimal(3,1) DEFAULT NULL,
  `CAPILLARYPCO2_AIR_MISS` tinyint(3) DEFAULT NULL,
  `BE` decimal(3,1) DEFAULT NULL,
  `BE_CAPILLARY` decimal(3,1) DEFAULT NULL,
  `BE_CAPILLARY_MISS` tinyint(3) DEFAULT NULL,
  `IS_CAPILLARY` tinyint(3) DEFAULT NULL,
  `BE_MISS` tinyint(3) DEFAULT NULL,
  `VC` decimal(3,2) DEFAULT NULL,
  `VC_MISS` tinyint(3) DEFAULT NULL,
  `VC_LYING` decimal(3,2) DEFAULT NULL,
  `VC_LYING_MISS` tinyint(3) DEFAULT NULL,
  `VC_SUPINE` decimal(3,2) DEFAULT NULL,
  `VC_SUPINE_MISS` tinyint(3) DEFAULT NULL,
  `FEV1` decimal(3,2) DEFAULT NULL,
  `FEV1_MISS` tinyint(3) DEFAULT NULL,
  `HOSTEPEF` smallint(6) DEFAULT NULL,
  `HOSTEPEF_MISS` tinyint(3) DEFAULT NULL,
  `HEIGHT` smallint(6) DEFAULT NULL,
  `HEIGHT_MISS` tinyint(3) DEFAULT NULL,
  `WEIGHT` decimal(4,1) DEFAULT NULL,
  `WEIGHT_MISS` tinyint(3) DEFAULT NULL,
  `VC_PERCENT_PREDICTED` decimal(4,1) DEFAULT NULL,
  `FEV1_PERCENT_PREDICTED` decimal(4,1) DEFAULT NULL,
  `DIAGNOSIS1` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `DIAGNOSIS1_OTHER_SPECIFY` varchar(150) COLLATE utf8_danish_ci DEFAULT NULL,
  `DIAGNOSIS2` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `DIAGNOSIS2_OTHER_SPECIFY` varchar(150) COLLATE utf8_danish_ci DEFAULT NULL,
  `SYMPTOM_HEADACHE` tinyint(3) DEFAULT NULL,
  `SYMPTOM_INSOMNIA` tinyint(3) DEFAULT NULL,
  `SYMPTOM_INFECTION_ETC` tinyint(3) DEFAULT NULL,
  `SYMPTOM_FATIGUE` tinyint(3) DEFAULT NULL,
  `SYMPTOM_DYSPNEA` tinyint(3) DEFAULT NULL,
  `STARTUP` tinyint(3) DEFAULT NULL,
  `HOSPITAL_DAYS_DISCHARGE` smallint(6) DEFAULT NULL,
  `SITUATION_VENTILATION` tinyint(3) DEFAULT NULL,
  `VENTILATION_HOURS` tinyint(3) DEFAULT NULL,
  `VENTILATION_METHOD` tinyint(3) DEFAULT NULL,
  `VENTILATION_FRENIKUS` tinyint(3) DEFAULT NULL,
  `RESPCON` tinyint(3) DEFAULT NULL,
  `TRAKEOSTOMI_DATE` date DEFAULT NULL,
  `VENTILATION_ASSISTANCE` tinyint(3) DEFAULT NULL,
  `QUALITYOFLIFE` tinyint(3) DEFAULT NULL,
  `QLWAKEUP` tinyint(3) DEFAULT NULL,
  `QLHEADACHE` tinyint(3) DEFAULT NULL,
  `QLRESTED` tinyint(3) DEFAULT NULL,
  `QLSLEEPY` tinyint(3) DEFAULT NULL,
  `QLDYSPNOEA` tinyint(3) DEFAULT NULL,
  `QLESS` tinyint(3) DEFAULT NULL,
  `ADDITIONAL_OXYGEN` tinyint(3) DEFAULT NULL,
  `ADDITIONAL_HUMIDIFIER` tinyint(3) DEFAULT NULL,
  `ADDITIONAL_SPARE_RESP` tinyint(3) DEFAULT NULL,
  `ADDITIONAL_SUCTION` tinyint(3) DEFAULT NULL,
  `ADDITIONAL_COUGH_MACHINE` tinyint(3) DEFAULT NULL,
  `ADDITIONAL_OXIMETER` tinyint(3) DEFAULT NULL,
  `ADDITIONAL_TUBE_FEEDING` tinyint(3) DEFAULT NULL,
  `RESIDENTIAL_FORM` tinyint(3) DEFAULT NULL,
  `ZIPCODE` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `TOWN` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `MUNICIPALITY_NUMBER` varchar(4) COLLATE utf8_danish_ci DEFAULT NULL,
  `MUNICIPALITY_NAME` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `COUNTY` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `WORK_STATUS` tinyint(3) DEFAULT NULL,
  `CARE_SERVICES_UNPAID_RELATIVES` tinyint(3) DEFAULT NULL,
  `CARE_SERVICES_PAID_RELATIVES` tinyint(3) DEFAULT NULL,
  `CARE_SERVICES_USER_PERS_ASSISTANT` tinyint(3) DEFAULT NULL,
  `CARE_SERVICES_SERVICE_HOUSING` tinyint(3) DEFAULT NULL,
  `CARE_SERVICES_TEAM` tinyint(3) DEFAULT NULL,
  `CARE_SERVICES_HOME_NURSING` tinyint(3) DEFAULT NULL,
  `CARE_SERVICES_UNKNOWN` tinyint(3) DEFAULT NULL,
  `USERCOMMENT` varchar(2000) COLLATE utf8_danish_ci DEFAULT NULL,
  `STATUS` tinyint(3) DEFAULT NULL,
  `TSUPDATED` timestamp NULL DEFAULT NULL,
  `UPDATEDBY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `FIRST_TIME_CLOSED` timestamp NULL DEFAULT NULL,
  `FIRST_TIME_CLOSED_BY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `TSCREATED` timestamp NULL DEFAULT NULL,
  `CREATEDBY` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  PRIMARY KEY (`MCEID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;
